!set variable_substitution=true;

-- Set context using environment variables
USE ROLE &SNOWSQL_ENVVAR_ROLE;

-- Create ANALYTICS database if not exists
CREATE DATABASE IF NOT EXISTS ANALYTICS
    COMMENT = 'Analytics database for dimensional modeling and analytical workloads';

-- Use the ANALYTICS database
USE DATABASE ANALYTICS;

-- Create default schema if not exists
CREATE SCHEMA IF NOT EXISTS PUBLIC
    COMMENT = 'Default public schema for analytics objects';

-- Create ANALYTICS specific schema
CREATE SCHEMA IF NOT EXISTS ANALYTICS
    COMMENT = 'Analytics schema for dimensional tables and analytical views';

-- Grant permissions to the current role
GRANT ALL ON DATABASE ANALYTICS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON SCHEMA ANALYTICS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON SCHEMA ANALYTICS.ANALYTICS TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant future object permissions
GRANT ALL ON ALL TABLES IN SCHEMA ANALYTICS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA ANALYTICS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL PROCEDURES IN SCHEMA ANALYTICS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA ANALYTICS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;

GRANT ALL ON ALL TABLES IN SCHEMA ANALYTICS.ANALYTICS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA ANALYTICS.ANALYTICS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL PROCEDURES IN SCHEMA ANALYTICS.ANALYTICS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA ANALYTICS.ANALYTICS TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant future permissions
GRANT ALL ON FUTURE TABLES IN SCHEMA ANALYTICS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA ANALYTICS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA ANALYTICS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA ANALYTICS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;

GRANT ALL ON FUTURE TABLES IN SCHEMA ANALYTICS.ANALYTICS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA ANALYTICS.ANALYTICS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA ANALYTICS.ANALYTICS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA ANALYTICS.ANALYTICS TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Set default schema for convenience
USE SCHEMA ANALYTICS.ANALYTICS;