-- Change History Information
-- VERSION:      1.0.3
-- DESCRIPTION:  Create views for school business reporting and analytics
-- CREATED:      2024-09-24
-- AUTHOR:       School Business Team
-- DEPENDENCIES: All table creation and data files
-- ENVIRONMENT:  ALL (DEV, QA, PROD)

!set variable_substitution=true;

USE ROLE SYSADMIN;
USE DATABASE SCHOOL_BUSINESS_DB;
USE SCHEMA SCHOOL_BUSINESS_SCHEMA;

-- Student enrollment summary view
CREATE OR REPLACE VIEW VW_STUDENT_ENROLLMENT_SUMMARY AS
SELECT 
    s.STUDENT_ID,
    s.FIRST_NAME || ' ' || s.LAST_NAME AS STUDENT_NAME,
    s.EMAIL AS STUDENT_EMAIL,
    s.ENROLLMENT_DATE,
    s.STATUS AS STUDENT_STATUS,
    COUNT(e.COURSE_ID) AS TOTAL_COURSES_ENROLLED,
    COUNT(CASE WHEN e.STATUS = 'COMPLETED' THEN 1 END) AS COMPLETED_COURSES,
    COUNT(CASE WHEN e.STATUS = 'ACTIVE' THEN 1 END) AS ACTIVE_COURSES,
    COUNT(CASE WHEN e.STATUS = 'DROPPED' THEN 1 END) AS DROPPED_COURSES,
    ROUND(AVG(CASE WHEN e.GRADE IS NOT NULL THEN e.GRADE END), 2) AS AVERAGE_GRADE,
    ROUND(AVG(CASE WHEN e.ATTENDANCE_PERCENTAGE IS NOT NULL THEN e.ATTENDANCE_PERCENTAGE END), 1) AS AVERAGE_ATTENDANCE,
    SUM(CASE WHEN e.STATUS IN ('COMPLETED', 'ACTIVE') THEN c.CREDITS ELSE 0 END) AS TOTAL_CREDITS
FROM STUDENTS s
LEFT JOIN ENROLLMENTS e ON s.STUDENT_ID = e.STUDENT_ID
LEFT JOIN COURSES c ON e.COURSE_ID = c.COURSE_ID
GROUP BY s.STUDENT_ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.ENROLLMENT_DATE, s.STATUS
COMMENT = 'Comprehensive summary of student enrollment status and performance';

-- Teacher course load and performance view
CREATE OR REPLACE VIEW VW_TEACHER_COURSE_LOAD AS
SELECT 
    t.TEACHER_ID,
    t.FIRST_NAME || ' ' || t.LAST_NAME AS TEACHER_NAME,
    t.SUBJECT,
    t.DEPARTMENT,
    t.EMAIL AS TEACHER_EMAIL,
    t.STATUS AS TEACHER_STATUS,
    COUNT(DISTINCT c.COURSE_ID) AS TOTAL_COURSES_TEACHING,
    COUNT(DISTINCT CASE WHEN c.STATUS = 'ACTIVE' THEN c.COURSE_ID END) AS ACTIVE_COURSES,
    COUNT(DISTINCT e.STUDENT_ID) AS TOTAL_STUDENTS,
    COUNT(DISTINCT CASE WHEN e.STATUS = 'ACTIVE' THEN e.STUDENT_ID END) AS ACTIVE_STUDENTS,
    ROUND(AVG(CASE WHEN e.GRADE IS NOT NULL THEN e.GRADE END), 2) AS AVERAGE_STUDENT_GRADE,
    ROUND(AVG(CASE WHEN e.ATTENDANCE_PERCENTAGE IS NOT NULL THEN e.ATTENDANCE_PERCENTAGE END), 1) AS AVERAGE_ATTENDANCE,
    SUM(c.CREDITS) AS TOTAL_CREDITS_TAUGHT
FROM TEACHERS t
LEFT JOIN COURSES c ON t.TEACHER_ID = c.TEACHER_ID
LEFT JOIN ENROLLMENTS e ON c.COURSE_ID = e.COURSE_ID
GROUP BY t.TEACHER_ID, t.FIRST_NAME, t.LAST_NAME, t.SUBJECT, t.DEPARTMENT, t.EMAIL, t.STATUS
COMMENT = 'Teacher workload and student performance metrics';

-- Course enrollment and performance details view
CREATE OR REPLACE VIEW VW_COURSE_ENROLLMENT_DETAILS AS
SELECT 
    c.COURSE_ID,
    c.COURSE_NAME,
    c.COURSE_CODE,
    c.CREDITS,
    c.SEMESTER,
    c.ACADEMIC_YEAR,
    c.MAX_ENROLLMENT,
    c.STATUS AS COURSE_STATUS,
    t.FIRST_NAME || ' ' || t.LAST_NAME AS INSTRUCTOR_NAME,
    t.DEPARTMENT,
    COUNT(e.STUDENT_ID) AS TOTAL_ENROLLED_STUDENTS,
    COUNT(CASE WHEN e.STATUS = 'ACTIVE' THEN 1 END) AS ACTIVE_STUDENTS,
    COUNT(CASE WHEN e.STATUS = 'COMPLETED' THEN 1 END) AS COMPLETED_STUDENTS,
    COUNT(CASE WHEN e.STATUS = 'DROPPED' THEN 1 END) AS DROPPED_STUDENTS,
    ROUND((COUNT(e.STUDENT_ID) * 100.0 / c.MAX_ENROLLMENT), 1) AS ENROLLMENT_PERCENTAGE,
    ROUND(AVG(CASE WHEN e.GRADE IS NOT NULL THEN e.GRADE END), 2) AS AVERAGE_GRADE,
    ROUND(AVG(CASE WHEN e.ATTENDANCE_PERCENTAGE IS NOT NULL THEN e.ATTENDANCE_PERCENTAGE END), 1) AS AVERAGE_ATTENDANCE,
    ROUND(AVG(CASE WHEN e.FINAL_EXAM_SCORE IS NOT NULL THEN e.FINAL_EXAM_SCORE END), 1) AS AVERAGE_FINAL_EXAM,
    ROUND(AVG(CASE WHEN e.MIDTERM_SCORE IS NOT NULL THEN e.MIDTERM_SCORE END), 1) AS AVERAGE_MIDTERM
FROM COURSES c
LEFT JOIN TEACHERS t ON c.TEACHER_ID = t.TEACHER_ID
LEFT JOIN ENROLLMENTS e ON c.COURSE_ID = e.COURSE_ID
GROUP BY c.COURSE_ID, c.COURSE_NAME, c.COURSE_CODE, c.CREDITS, c.SEMESTER, c.ACADEMIC_YEAR, 
         c.MAX_ENROLLMENT, c.STATUS, t.FIRST_NAME, t.LAST_NAME, t.DEPARTMENT
COMMENT = 'Detailed course metrics including enrollment and performance statistics';

-- Department summary view
CREATE OR REPLACE VIEW VW_DEPARTMENT_SUMMARY AS
SELECT 
    t.DEPARTMENT,
    COUNT(DISTINCT t.TEACHER_ID) AS TOTAL_TEACHERS,
    COUNT(DISTINCT CASE WHEN t.STATUS = 'ACTIVE' THEN t.TEACHER_ID END) AS ACTIVE_TEACHERS,
    COUNT(DISTINCT c.COURSE_ID) AS TOTAL_COURSES,
    COUNT(DISTINCT CASE WHEN c.STATUS = 'ACTIVE' THEN c.COURSE_ID END) AS ACTIVE_COURSES,
    COUNT(DISTINCT e.STUDENT_ID) AS TOTAL_STUDENTS_ENROLLED,
    ROUND(AVG(t.SALARY), 2) AS AVERAGE_TEACHER_SALARY,
    ROUND(AVG(CASE WHEN e.GRADE IS NOT NULL THEN e.GRADE END), 2) AS DEPARTMENT_AVERAGE_GRADE,
    SUM(c.CREDITS) AS TOTAL_CREDITS_OFFERED
FROM TEACHERS t
LEFT JOIN COURSES c ON t.TEACHER_ID = c.TEACHER_ID
LEFT JOIN ENROLLMENTS e ON c.COURSE_ID = e.COURSE_ID
WHERE t.DEPARTMENT IS NOT NULL
GROUP BY t.DEPARTMENT
COMMENT = 'Department-level statistics and performance metrics';

-- Student transcript view (detailed academic record)
CREATE OR REPLACE VIEW VW_STUDENT_TRANSCRIPT AS
SELECT 
    s.STUDENT_ID,
    s.FIRST_NAME || ' ' || s.LAST_NAME AS STUDENT_NAME,
    s.EMAIL AS STUDENT_EMAIL,
    c.COURSE_CODE,
    c.COURSE_NAME,
    c.CREDITS,
    c.SEMESTER,
    c.ACADEMIC_YEAR,
    t.FIRST_NAME || ' ' || t.LAST_NAME AS INSTRUCTOR_NAME,
    e.ENROLLMENT_DATE,
    e.GRADE,
    e.LETTER_GRADE,
    e.STATUS AS ENROLLMENT_STATUS,
    e.ATTENDANCE_PERCENTAGE,
    e.FINAL_EXAM_SCORE,
    e.MIDTERM_SCORE
FROM STUDENTS s
JOIN ENROLLMENTS e ON s.STUDENT_ID = e.STUDENT_ID
JOIN COURSES c ON e.COURSE_ID = c.COURSE_ID
LEFT JOIN TEACHERS t ON c.TEACHER_ID = t.TEACHER_ID
COMMENT = 'Complete academic transcript for each student';

-- Academic performance analytics view
CREATE OR REPLACE VIEW VW_ACADEMIC_PERFORMANCE_ANALYTICS AS
SELECT 
    'Overall' AS CATEGORY,
    'All Students' AS SUBCATEGORY,
    COUNT(DISTINCT s.STUDENT_ID) AS STUDENT_COUNT,
    COUNT(DISTINCT e.COURSE_ID) AS COURSE_COUNT,
    COUNT(e.ENROLLMENT_ID) AS TOTAL_ENROLLMENTS,
    ROUND(AVG(CASE WHEN e.GRADE IS NOT NULL THEN e.GRADE END), 2) AS AVERAGE_GPA,
    ROUND(AVG(CASE WHEN e.ATTENDANCE_PERCENTAGE IS NOT NULL THEN e.ATTENDANCE_PERCENTAGE END), 1) AS AVERAGE_ATTENDANCE,
    COUNT(CASE WHEN e.STATUS = 'COMPLETED' AND e.GRADE >= 3.0 THEN 1 END) AS PASSING_GRADES,
    COUNT(CASE WHEN e.STATUS = 'COMPLETED' AND e.GRADE < 2.0 THEN 1 END) AS FAILING_GRADES,
    ROUND((COUNT(CASE WHEN e.STATUS = 'DROPPED' THEN 1 END) * 100.0 / COUNT(e.ENROLLMENT_ID)), 1) AS DROP_RATE_PERCENT
FROM STUDENTS s
LEFT JOIN ENROLLMENTS e ON s.STUDENT_ID = e.STUDENT_ID

UNION ALL

SELECT 
    'By Department' AS CATEGORY,
    COALESCE(t.DEPARTMENT, 'Unknown') AS SUBCATEGORY,
    COUNT(DISTINCT e.STUDENT_ID) AS STUDENT_COUNT,
    COUNT(DISTINCT c.COURSE_ID) AS COURSE_COUNT,
    COUNT(e.ENROLLMENT_ID) AS TOTAL_ENROLLMENTS,
    ROUND(AVG(CASE WHEN e.GRADE IS NOT NULL THEN e.GRADE END), 2) AS AVERAGE_GPA,
    ROUND(AVG(CASE WHEN e.ATTENDANCE_PERCENTAGE IS NOT NULL THEN e.ATTENDANCE_PERCENTAGE END), 1) AS AVERAGE_ATTENDANCE,
    COUNT(CASE WHEN e.STATUS = 'COMPLETED' AND e.GRADE >= 3.0 THEN 1 END) AS PASSING_GRADES,
    COUNT(CASE WHEN e.STATUS = 'COMPLETED' AND e.GRADE < 2.0 THEN 1 END) AS FAILING_GRADES,
    ROUND((COUNT(CASE WHEN e.STATUS = 'DROPPED' THEN 1 END) * 100.0 / COUNT(e.ENROLLMENT_ID)), 1) AS DROP_RATE_PERCENT
FROM ENROLLMENTS e
JOIN COURSES c ON e.COURSE_ID = c.COURSE_ID
LEFT JOIN TEACHERS t ON c.TEACHER_ID = t.TEACHER_ID
WHERE t.DEPARTMENT IS NOT NULL
GROUP BY t.DEPARTMENT
COMMENT = 'Comprehensive academic performance analytics by various categories';

-- Grant view permissions to roles
GRANT SELECT ON ALL VIEWS IN SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

-- Grant future view permissions
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;