!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Create CURATED schema if not exists
CREATE SCHEMA IF NOT EXISTS CURATED
    COMMENT = 'Curated schema for business-ready, high-quality data';

USE SCHEMA CURATED;

-- Create curated customers table
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_KEY VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    FULL_NAME VARCHAR(200),
    EMAIL VARCHAR(255),
    EMAIL_DOMAIN VARCHAR(100),
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    CUSTOMER_SEGMENT VARCHAR(50),
    CUSTOMER_TIER VARCHAR(20),
    REGISTRATION_DATE DATE,
    CUSTOMER_AGE_DAYS NUMBER(38,0),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    LIFETIME_VALUE NUMBER(12,2) DEFAULT 0,
    TOTAL_ORDERS NUMBER(38,0) DEFAULT 0,
    LAST_ORDER_DATE DATE,
    PREFERRED_CHANNEL VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UK_CUSTOMER_KEY UNIQUE (CUSTOMER_KEY),
    CONSTRAINT UK_CUSTOMER_EMAIL UNIQUE (EMAIL)
)
COMMENT = 'Curated customer master data for business consumption';

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS IDX_CUSTOMERS_SEGMENT ON CUSTOMERS(CUSTOMER_SEGMENT);
CREATE INDEX IF NOT EXISTS IDX_CUSTOMERS_TIER ON CUSTOMERS(CUSTOMER_TIER);
CREATE INDEX IF NOT EXISTS IDX_CUSTOMERS_EMAIL_DOMAIN ON CUSTOMERS(EMAIL_DOMAIN);
CREATE INDEX IF NOT EXISTS IDX_CUSTOMERS_REGISTRATION ON CUSTOMERS(REGISTRATION_DATE);