!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use CURATED schema
USE SCHEMA CURATED;

-- Create curated orders table
CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_STATUS VARCHAR(50),
    TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
    CURRENCY_CODE VARCHAR(3) DEFAULT 'USD',
    PAYMENT_METHOD VARCHAR(50),
    SHIPPING_ADDRESS VARCHAR(500),
    BILLING_ADDRESS VARCHAR(500),
    SALES_CHANNEL VARCHAR(50),
    SALES_REP_ID NUMBER(38,0),
    REGION VARCHAR(100),
    ORDER_YEAR NUMBER(4,0),
    ORDER_MONTH NUMBER(2,0),
    ORDER_QUARTER NUMBER(1,0),
    IS_HOLIDAY_ORDER BOOLEAN DEFAULT FALSE,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID)
)
COMMENT = 'Curated orders data for business consumption';

-- Create indexes
CREATE INDEX IF NOT EXISTS IDX_ORDERS_CUSTOMER ON ORDERS(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IDX_ORDERS_DATE ON ORDERS(ORDER_DATE);
CREATE INDEX IF NOT EXISTS IDX_ORDERS_STATUS ON ORDERS(ORDER_STATUS);
CREATE INDEX IF NOT EXISTS IDX_ORDERS_CHANNEL ON ORDERS(SALES_CHANNEL);