-- Setup Service Account for CICD Deployments
-- This script creates a service account and assigns necessary roles for CICD pipeline

-- Create DEV role first
CREATE ROLE IF NOT EXISTS DEV_ROLE
    COMMENT = 'Role for development environment access';

-- Create service account
CREATE USER IF NOT EXISTS etlsnowflakecicd
    PASSWORD =''
    COMMENT = 'Service account for CICD deployments'
    MUST_CHANGE_PASSWORD = FALSE;

-- Create CICD deployment role
CREATE ROLE IF NOT EXISTS CICD_DEPLOYMENT_ROLE
    COMMENT = 'Role for CICD deployment operations';

-- Create required objects if they don't exist
CREATE WAREHOUSE IF NOT EXISTS DEV_WH;
CREATE DATABASE IF NOT EXISTS DEV_DB;

-- Grant necessary privileges to DEV role
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE DEV_ROLE;
GRANT ALL ON DATABASE DEV_DB TO ROLE DEV_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE DEV_DB TO ROLE DEV_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE DEV_DB TO ROLE DEV_ROLE;
GRANT ALL ON ALL TABLES IN DATABASE DEV_DB TO ROLE DEV_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE DEV_DB TO ROLE DEV_ROLE;

-- Grant necessary privileges to CICD role for DEV environment
GRANT ROLE DEV_ROLE TO ROLE CICD_DEPLOYMENT_ROLE;
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE CICD_DEPLOYMENT_ROLE;
GRANT ALL ON DATABASE DEV_DB TO ROLE CICD_DEPLOYMENT_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE DEV_DB TO ROLE CICD_DEPLOYMENT_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE DEV_DB TO ROLE CICD_DEPLOYMENT_ROLE;
GRANT ALL ON ALL TABLES IN DATABASE DEV_DB TO ROLE CICD_DEPLOYMENT_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE DEV_DB TO ROLE CICD_DEPLOYMENT_ROLE;

-- Grant CICD role to service account
GRANT ROLE CICD_DEPLOYMENT_ROLE TO USER etlsnowflakecicd;

-- Set default role for service account
ALTER USER etlsnowflakecicd SET DEFAULT_ROLE = CICD_DEPLOYMENT_ROLE;