-- Setup Service Account for CICD Deployments
-- This script creates a service account and assigns necessary roles for CICD pipeline

-- Create QA role first
CREATE ROLE IF NOT EXISTS QA_ROLE
    COMMENT = 'Role for QAelopment environment access';

-- Create service account
CREATE USER IF NOT EXISTS etlsnowflakecicd
    PASSWORD =''
    COMMENT = 'Service account for CICD deployments'
    MUST_CHANGE_PASSWORD = FALSE;

-- Create CICD deployment role
CREATE ROLE IF NOT EXISTS CICD_DEPLOYMENT_ROLE
    COMMENT = 'Role for CICD deployment operations';

-- Create required objects if they don't exist
CREATE WAREHOUSE IF NOT EXISTS QA_WH;
CREATE DATABASE IF NOT EXISTS QA_DB;

-- Grant necessary privileges to QA role
GRANT USAGE ON WAREHOUSE QA_WH TO ROLE QA_ROLE;
GRANT ALL ON DATABASE QA_DB TO ROLE QA_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE QA_DB TO ROLE QA_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE QA_DB TO ROLE QA_ROLE;
GRANT ALL ON ALL TABLES IN DATABASE QA_DB TO ROLE QA_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE QA_DB TO ROLE QA_ROLE;

-- Grant necessary privileges to CICD role for QA environment
GRANT ROLE QA_ROLE TO ROLE CICD_DEPLOYMENT_ROLE;
GRANT USAGE ON WAREHOUSE QA_WH TO ROLE CICD_DEPLOYMENT_ROLE;
GRANT ALL ON DATABASE QA_DB TO ROLE CICD_DEPLOYMENT_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE QA_DB TO ROLE CICD_DEPLOYMENT_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE QA_DB TO ROLE CICD_DEPLOYMENT_ROLE;
GRANT ALL ON ALL TABLES IN DATABASE QA_DB TO ROLE CICD_DEPLOYMENT_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE QA_DB TO ROLE CICD_DEPLOYMENT_ROLE;

-- Grant CICD role to service account
GRANT ROLE CICD_DEPLOYMENT_ROLE TO USER etlsnowflakecicd;

-- Set default role for service account
ALTER USER etlsnowflakecicd SET DEFAULT_ROLE = CICD_DEPLOYMENT_ROLE;