!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Create RAW schema if not exists
CREATE SCHEMA IF NOT EXISTS RAW
    COMMENT = 'Raw data schema for ingested source data';

USE SCHEMA RAW;

-- Create raw customers table
CREATE TABLE IF NOT EXISTS RAW_CUSTOMERS (
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_KEY VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    CUSTOMER_SEGMENT VARCHAR(50),
    REGISTRATION_DATE DATE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'CRM',
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(255),
    ROW_NUMBER NUMBER(38,0),
    CONSTRAINT PK_RAW_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
)
COMMENT = 'Raw customer data from source systems';