!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use RAW schema
USE SCHEMA RAW;

-- Create raw orders table
CREATE TABLE IF NOT EXISTS RAW_ORDERS (
    ORDER_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_STATUS VARCHAR(50),
    TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
    CURRENCY_CODE VARCHAR(3) DEFAULT 'USD',
    PAYMENT_METHOD VARCHAR(50),
    SHIPPING_ADDRESS VARCHAR(500),
    BILLING_ADDRESS VARCHAR(500),
    SALES_CHANNEL VARCHAR(50),
    SALES_REP_ID NUMBER(38,0),
    REGION VARCHAR(100),
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'ERP',
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(255),
    ROW_NUMBER NUMBER(38,0),
    CONSTRAINT PK_RAW_ORDERS PRIMARY KEY (ORDER_ID)
)
COMMENT = 'Raw order data from source systems';