!set variable_substitution=true;

-- Set context using environment variables
USE ROLE &SNOWSQL_ENVVAR_ROLE;

-- Create REPORTING database if not exists
CREATE DATABASE IF NOT EXISTS REPORTING
    COMMENT = 'Reporting database for business intelligence and analytical reporting';

-- Use the REPORTING database
USE DATABASE REPORTING;

-- Create default schema if not exists
CREATE SCHEMA IF NOT EXISTS PUBLIC
    COMMENT = 'Default public schema for reporting objects';

-- Create REPORTING specific schema
CREATE SCHEMA IF NOT EXISTS REPORTING
    COMMENT = 'Reporting schema for report tables, views, and export functions';

-- Create DASHBOARDS schema for dashboard-specific objects
CREATE SCHEMA IF NOT EXISTS DASHBOARDS
    COMMENT = 'Dashboard schema for dashboard-specific views and materialized views';

-- Create EXPORTS schema for data export functionality
CREATE SCHEMA IF NOT EXISTS EXPORTS
    COMMENT = 'Exports schema for data export tables and staging areas';

-- Grant database permissions to the current role
GRANT ALL ON DATABASE REPORTING TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant schema permissions
GRANT ALL ON SCHEMA REPORTING.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON SCHEMA REPORTING.REPORTING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON SCHEMA REPORTING.DASHBOARDS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON SCHEMA REPORTING.EXPORTS TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant current object permissions for PUBLIC schema
GRANT ALL ON ALL TABLES IN SCHEMA REPORTING.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA REPORTING.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL PROCEDURES IN SCHEMA REPORTING.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA REPORTING.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant current object permissions for REPORTING schema
GRANT ALL ON ALL TABLES IN SCHEMA REPORTING.REPORTING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA REPORTING.REPORTING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL PROCEDURES IN SCHEMA REPORTING.REPORTING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA REPORTING.REPORTING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL FILE FORMATS IN SCHEMA REPORTING.REPORTING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL STAGES IN SCHEMA REPORTING.REPORTING TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant current object permissions for DASHBOARDS schema
GRANT ALL ON ALL TABLES IN SCHEMA REPORTING.DASHBOARDS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA REPORTING.DASHBOARDS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL PROCEDURES IN SCHEMA REPORTING.DASHBOARDS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA REPORTING.DASHBOARDS TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant current object permissions for EXPORTS schema
GRANT ALL ON ALL TABLES IN SCHEMA REPORTING.EXPORTS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA REPORTING.EXPORTS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL PROCEDURES IN SCHEMA REPORTING.EXPORTS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA REPORTING.EXPORTS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL FILE FORMATS IN SCHEMA REPORTING.EXPORTS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL STAGES IN SCHEMA REPORTING.EXPORTS TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant future object permissions for PUBLIC schema
GRANT ALL ON FUTURE TABLES IN SCHEMA REPORTING.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA REPORTING.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA REPORTING.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA REPORTING.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant future object permissions for REPORTING schema
GRANT ALL ON FUTURE TABLES IN SCHEMA REPORTING.REPORTING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA REPORTING.REPORTING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA REPORTING.REPORTING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA REPORTING.REPORTING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA REPORTING.REPORTING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE STAGES IN SCHEMA REPORTING.REPORTING TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant future object permissions for DASHBOARDS schema
GRANT ALL ON FUTURE TABLES IN SCHEMA REPORTING.DASHBOARDS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA REPORTING.DASHBOARDS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA REPORTING.DASHBOARDS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA REPORTING.DASHBOARDS TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant future object permissions for EXPORTS schema
GRANT ALL ON FUTURE TABLES IN SCHEMA REPORTING.EXPORTS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA REPORTING.EXPORTS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA REPORTING.EXPORTS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA REPORTING.EXPORTS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA REPORTING.EXPORTS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE STAGES IN SCHEMA REPORTING.EXPORTS TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Set default schema for convenience
USE SCHEMA REPORTING.REPORTING;