//Create a snow flake based schema for a school business database also use appropriate data types and constraints and create seperate read and read write roles and also create a read user and read write user and assign the roles to them

-- Switch to ACCOUNTADMIN for user and role creation
USE ROLE ACCOUNTADMIN;

-- Create custom roles first
CREATE ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
CREATE ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

-- Grant custom roles to SYSADMIN (best practice)
GRANT ROLE SCHOOL_BUSINESS_DB_READ_ROLE TO ROLE SYSADMIN;
GRANT ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE TO ROLE SYSADMIN;

-- Switch to SYSADMIN for database and warehouse creation
USE ROLE SYSADMIN;

CREATE DATABASE SCHOOL_BUSINESS_DB;
USE DATABASE SCHOOL_BUSINESS_DB; 
CREATE SCHEMA SCHOOL_BUSINESS_SCHEMA;

-- Create a warehouse for the school business operations
CREATE WAREHOUSE SCHOOL_BUSINESS_WH WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Switch back to ACCOUNTADMIN for user creation
USE ROLE ACCOUNTADMIN;
CREATE USER SCHOOL_BUSINESS_DB_READ_USER PASSWORD='ReadUserPass123' DEFAULT_ROLE=SCHOOL_BUSINESS_DB_READ_ROLE DEFAULT_WAREHOUSE=SCHOOL_BUSINESS_WH;
CREATE USER SCHOOL_BUSINESS_DB_READ_WRITE_USER PASSWORD='ReadWriteUserPass123' DEFAULT_ROLE=SCHOOL_BUSINESS_DB_READ_WRITE_ROLE DEFAULT_WAREHOUSE=SCHOOL_BUSINESS_WH;
GRANT ROLE SCHOOL_BUSINESS_DB_READ_ROLE TO USER SCHOOL_BUSINESS_DB_READ_USER;
GRANT ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE TO USER SCHOOL_BUSINESS_DB_READ_WRITE_USER;
GRANT ROLE SCHOOL_BUSINESS_DB_READ_ROLE TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

-- Switch to SYSADMIN for table creation
USE ROLE SYSADMIN;
USE DATABASE SCHOOL_BUSINESS_DB;
USE SCHEMA SCHOOL_BUSINESS_SCHEMA;
CREATE TABLE STUDENTS (
    STUDENT_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(15),
    ADDRESS VARCHAR(255),
    ENROLLMENT_DATE DATE NOT NULL
);
CREATE TABLE TEACHERS (
    TEACHER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(15),
    HIRE_DATE DATE NOT NULL,
    SUBJECT VARCHAR(100) NOT NULL
);
CREATE TABLE COURSES (
    COURSE_ID INT PRIMARY KEY,
    COURSE_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    CREDITS INT NOT NULL,
    TEACHER_ID INT,
    FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS(TEACHER_ID)
);
CREATE TABLE ENROLLMENTS (
    ENROLLMENT_ID INT PRIMARY KEY,
    STUDENT_ID INT,
    COURSE_ID INT,
    ENROLLMENT_DATE DATE NOT NULL,
    GRADE DECIMAL(3, 2),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID)
);

//Create sample data to insert into the tables
INSERT INTO STUDENTS (STUDENT_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL, PHONE_NUMBER, ADDRESS, ENROLLMENT_DATE) VALUES
(1, 'John', 'Doe', '2005-05-15', 'john.doe@example.com', '123-456-7890', '123 Main St, Anytown, USA', '2021-09-01'),
(2, 'Jane', 'Smith', '2006-08-22', 'jane.smith@example.com', '987-654-3210', '456 Elm St, Othertown, USA', '2021-09-01');
INSERT INTO TEACHERS (TEACHER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, SUBJECT) VALUES
(1, 'Alice', 'Johnson', 'alice.johnson@example.com', '555-123-4567', '2020-01-15', 'Mathematics'),
(2, 'Bob', 'Williams', 'bob.williams@example.com', '555-987-6543', '2019-08-01', 'Physics');
INSERT INTO COURSES (COURSE_ID, COURSE_NAME, DESCRIPTION, CREDITS, TEACHER_ID) VALUES
(1, 'Algebra I', 'Introduction to Algebra', 3, 1),
(2, 'Physics I', 'Fundamentals of Physics', 4, 2);

INSERT INTO ENROLLMENTS (ENROLLMENT_ID, STUDENT_ID, COURSE_ID, ENROLLMENT_DATE, GRADE) VALUES
(1, 1, 1, '2021-09-01', 3.5),
(2, 1, 2, '2021-09-01', 3.8),
(3, 2, 1, '2021-09-01', 3.9),
(4, 2, 2, '2021-09-01', 4.0);

-- Grant permissions (SYSADMIN can grant on objects it owns)
-- Grant database usage to both roles
GRANT USAGE ON DATABASE SCHOOL_BUSINESS_DB TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT USAGE ON DATABASE SCHOOL_BUSINESS_DB TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

-- Grant warehouse usage to both roles
GRANT USAGE ON WAREHOUSE SCHOOL_BUSINESS_WH TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT USAGE ON WAREHOUSE SCHOOL_BUSINESS_WH TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

-- Grant OPERATE privilege on warehouse (allows starting/stopping the warehouse)
GRANT OPERATE ON WAREHOUSE SCHOOL_BUSINESS_WH TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT OPERATE ON WAREHOUSE SCHOOL_BUSINESS_WH TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

-- Grant schema usage and permissions
GRANT USAGE ON SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT USAGE ON SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

-- Grant table permissions to READ_ROLE
GRANT SELECT ON ALL TABLES IN SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;

-- Grant table permissions to READ_WRITE_ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

-- Grant schema-level permissions to READ_WRITE_ROLE
GRANT CREATE TABLE ON SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;
GRANT CREATE VIEW ON SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;
GRANT CREATE STAGE ON SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;
GRANT CREATE PIPE ON SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;





// I am testing out the permissions so create the delete statement to start clean

-- CLEANUP STATEMENTS - Run these to start clean for testing
-- Use ACCOUNTADMIN for cleanup
USE ROLE ACCOUNTADMIN;

-- Drop users first (need to drop them before dropping roles they're assigned to)
DROP USER IF EXISTS SCHOOL_BUSINESS_DB_READ_USER;
DROP USER IF EXISTS SCHOOL_BUSINESS_DB_READ_WRITE_USER;

-- Drop roles
DROP ROLE IF EXISTS SCHOOL_BUSINESS_DB_READ_ROLE;
DROP ROLE IF EXISTS SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

-- Switch to SYSADMIN to drop warehouse and database
USE ROLE SYSADMIN;

-- Drop warehouse
DROP WAREHOUSE IF EXISTS SCHOOL_BUSINESS_WH;

-- Drop database (this will cascade and drop schema and all tables)
DROP DATABASE IF EXISTS SCHOOL_BUSINESS_DB;