!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use REPORTING schema
USE SCHEMA REPORTING;

-- Create customer performance report table
CREATE TABLE IF NOT EXISTS RPT_CUSTOMER_PERFORMANCE (
    PERFORMANCE_ID NUMBER(38,0) AUTOINCREMENT,
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    REPORT_PERIOD VARCHAR(7) NOT NULL, -- Format: YYYY-MM
    CUSTOMER_SEGMENT VARCHAR(50),
    TOTAL_ORDERS NUMBER(38,0) DEFAULT 0,
    TOTAL_SPEND NUMBER(15,2) DEFAULT 0,
    AVERAGE_ORDER_VALUE NUMBER(10,2) DEFAULT 0,
    DAYS_SINCE_LAST_ORDER NUMBER(10,0),
    CUSTOMER_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    LIFETIME_VALUE NUMBER(15,2) DEFAULT 0,
    CREATED_DATE DATE DEFAULT CURRENT_DATE(),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_RPT_CUSTOMER_PERFORMANCE PRIMARY KEY (PERFORMANCE_ID),
    CONSTRAINT UK_CUSTOMER_PERFORMANCE UNIQUE (CUSTOMER_ID, REPORT_PERIOD)
)
COMMENT = 'Customer performance metrics report table';

-- Create indexes
CREATE INDEX IF NOT EXISTS IDX_RPT_CUSTOMER_PERFORMANCE_PERIOD ON RPT_CUSTOMER_PERFORMANCE(REPORT_PERIOD);
CREATE INDEX IF NOT EXISTS IDX_RPT_CUSTOMER_PERFORMANCE_SEGMENT ON RPT_CUSTOMER_PERFORMANCE(CUSTOMER_SEGMENT);
CREATE INDEX IF NOT EXISTS IDX_RPT_CUSTOMER_PERFORMANCE_STATUS ON RPT_CUSTOMER_PERFORMANCE(CUSTOMER_STATUS);