!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Create REPORTING schema if not exists
CREATE SCHEMA IF NOT EXISTS REPORTING
    COMMENT = 'Reporting schema for business reports and dashboards';

USE SCHEMA REPORTING;

-- Create monthly sales report table
CREATE TABLE IF NOT EXISTS RPT_MONTHLY_SALES (
    REPORT_ID NUMBER(38,0) AUTOINCREMENT,
    YEAR_MONTH VARCHAR(7) NOT NULL, -- Format: YYYY-MM
    SALES_CHANNEL VARCHAR(50),
    REGION VARCHAR(100),
    TOTAL_ORDERS NUMBER(38,0) NOT NULL,
    TOTAL_CUSTOMERS NUMBER(38,0) NOT NULL,
    TOTAL_REVENUE NUMBER(15,2) NOT NULL,
    TOTAL_QUANTITY NUMBER(15,2) NOT NULL,
    AVG_ORDER_VALUE NUMBER(10,2) NOT NULL,
    DISCOUNT_PERCENTAGE NUMBER(5,2) DEFAULT 0,
    CREATED_DATE DATE DEFAULT CURRENT_DATE(),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_RPT_MONTHLY_SALES PRIMARY KEY (REPORT_ID),
    CONSTRAINT UK_MONTHLY_SALES UNIQUE (YEAR_MONTH, SALES_CHANNEL, REGION)
)
COMMENT = 'Monthly sales summary report table';

-- Create indexes for reporting queries
CREATE INDEX IF NOT EXISTS IDX_RPT_MONTHLY_SALES_PERIOD ON RPT_MONTHLY_SALES(YEAR_MONTH);
CREATE INDEX IF NOT EXISTS IDX_RPT_MONTHLY_SALES_CHANNEL ON RPT_MONTHLY_SALES(SALES_CHANNEL);