-- Change History Information
-- VERSION:      1.0.1
-- DESCRIPTION:  Create COURSES table for school business database
-- CREATED:      2024-09-24
-- AUTHOR:       School Business Team
-- DEPENDENCIES: V1.0.0__school_business_setup.sql, teachers.sql
-- ENVIRONMENT:  ALL (DEV, QA, PROD)

!set variable_substitution=true;

USE ROLE SYSADMIN;
USE DATABASE SCHOOL_BUSINESS_DB;
USE SCHEMA SCHOOL_BUSINESS_SCHEMA;

-- Create Courses table
CREATE TABLE IF NOT EXISTS COURSES (
    COURSE_ID INT AUTOINCREMENT PRIMARY KEY,
    COURSE_NAME VARCHAR(100) NOT NULL,
    COURSE_CODE VARCHAR(20) UNIQUE NOT NULL,
    DESCRIPTION TEXT,
    CREDITS INT NOT NULL CHECK (CREDITS > 0 AND CREDITS <= 6),
    TEACHER_ID INT,
    SEMESTER VARCHAR(20),
    ACADEMIC_YEAR VARCHAR(10),
    MAX_ENROLLMENT INT DEFAULT 30,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'CANCELLED')),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT CHK_COURSES_MAX_ENROLLMENT CHECK (MAX_ENROLLMENT > 0),
    FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS(TEACHER_ID)
) COMMENT = 'Course information including instructor and scheduling details';

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS IDX_COURSES_CODE ON COURSES(COURSE_CODE);
CREATE INDEX IF NOT EXISTS IDX_COURSES_TEACHER ON COURSES(TEACHER_ID);
CREATE INDEX IF NOT EXISTS IDX_COURSES_SEMESTER ON COURSES(SEMESTER);
CREATE INDEX IF NOT EXISTS IDX_COURSES_STATUS ON COURSES(STATUS);

-- Grant permissions to roles
GRANT SELECT ON TABLE COURSES TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE COURSES TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;