-- Change History Information
-- VERSION:      1.0.1
-- DESCRIPTION:  Create ENROLLMENTS table for school business database
-- CREATED:      2024-09-24
-- AUTHOR:       School Business Team
-- DEPENDENCIES: V1.0.0__school_business_setup.sql, students.sql, courses.sql
-- ENVIRONMENT:  ALL (DEV, QA, PROD)

!set variable_substitution=true;

USE ROLE SYSADMIN;
USE DATABASE SCHOOL_BUSINESS_DB;
USE SCHEMA SCHOOL_BUSINESS_SCHEMA;

-- Create Enrollments table
CREATE TABLE IF NOT EXISTS ENROLLMENTS (
    ENROLLMENT_ID INT AUTOINCREMENT PRIMARY KEY,
    STUDENT_ID INT NOT NULL,
    COURSE_ID INT NOT NULL,
    ENROLLMENT_DATE DATE NOT NULL DEFAULT CURRENT_DATE(),
    GRADE DECIMAL(3, 2) CHECK (GRADE >= 0.0 AND GRADE <= 4.0),
    LETTER_GRADE VARCHAR(2),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'COMPLETED', 'DROPPED', 'WITHDRAWN', 'FAILED')),
    ATTENDANCE_PERCENTAGE DECIMAL(5, 2) CHECK (ATTENDANCE_PERCENTAGE >= 0 AND ATTENDANCE_PERCENTAGE <= 100),
    FINAL_EXAM_SCORE DECIMAL(5, 2),
    MIDTERM_SCORE DECIMAL(5, 2),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT CHK_ENROLLMENTS_ENROLLMENT_DATE CHECK (ENROLLMENT_DATE <= CURRENT_DATE()),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID),
    UNIQUE (STUDENT_ID, COURSE_ID)
) COMMENT = 'Student course enrollments with grades and attendance tracking';

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS IDX_ENROLLMENTS_STUDENT ON ENROLLMENTS(STUDENT_ID);
CREATE INDEX IF NOT EXISTS IDX_ENROLLMENTS_COURSE ON ENROLLMENTS(COURSE_ID);
CREATE INDEX IF NOT EXISTS IDX_ENROLLMENTS_STATUS ON ENROLLMENTS(STATUS);
CREATE INDEX IF NOT EXISTS IDX_ENROLLMENTS_DATE ON ENROLLMENTS(ENROLLMENT_DATE);

-- Grant permissions to roles
GRANT SELECT ON TABLE ENROLLMENTS TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ENROLLMENTS TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;