-- Change History Information
-- VERSION:      1.0.1
-- DESCRIPTION:  Create STUDENTS table for school business database
-- CREATED:      2024-09-24
-- AUTHOR:       School Business Team
-- DEPENDENCIES: V1.0.0__school_business_setup.sql
-- ENVIRONMENT:  ALL (DEV, QA, PROD)

!set variable_substitution=true;

USE ROLE SYSADMIN;
USE DATABASE SCHOOL_BUSINESS_DB;
USE SCHEMA SCHOOL_BUSINESS_SCHEMA;

-- Create Students table
CREATE TABLE IF NOT EXISTS STUDENTS (
    STUDENT_ID INT AUTOINCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(15),
    ADDRESS VARCHAR(255),
    ENROLLMENT_DATE DATE NOT NULL DEFAULT CURRENT_DATE(),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'GRADUATED', 'TRANSFERRED')),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT CHK_STUDENTS_EMAIL CHECK (EMAIL LIKE '%@%'),
    CONSTRAINT CHK_STUDENTS_BIRTH_DATE CHECK (DATE_OF_BIRTH < CURRENT_DATE()),
    CONSTRAINT CHK_STUDENTS_ENROLLMENT_DATE CHECK (ENROLLMENT_DATE <= CURRENT_DATE())
) COMMENT = 'Student information and enrollment details';

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS IDX_STUDENTS_EMAIL ON STUDENTS(EMAIL);
CREATE INDEX IF NOT EXISTS IDX_STUDENTS_STATUS ON STUDENTS(STATUS);
CREATE INDEX IF NOT EXISTS IDX_STUDENTS_ENROLLMENT_DATE ON STUDENTS(ENROLLMENT_DATE);

-- Grant permissions to roles
GRANT SELECT ON TABLE STUDENTS TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STUDENTS TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;