-- Change History Information
-- VERSION:      1.0.1
-- DESCRIPTION:  Create TEACHERS table for school business database
-- CREATED:      2024-09-24
-- AUTHOR:       School Business Team
-- DEPENDENCIES: V1.0.0__school_business_setup.sql
-- ENVIRONMENT:  ALL (DEV, QA, PROD)

!set variable_substitution=true;

USE ROLE SYSADMIN;
USE DATABASE SCHOOL_BUSINESS_DB;
USE SCHEMA SCHOOL_BUSINESS_SCHEMA;

-- Create Teachers table
CREATE TABLE IF NOT EXISTS TEACHERS (
    TEACHER_ID INT AUTOINCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(15),
    HIRE_DATE DATE NOT NULL,
    SUBJECT VARCHAR(100) NOT NULL,
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10, 2),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'TERMINATED', 'RETIRED')),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT CHK_TEACHERS_EMAIL CHECK (EMAIL LIKE '%@%'),
    CONSTRAINT CHK_TEACHERS_HIRE_DATE CHECK (HIRE_DATE <= CURRENT_DATE()),
    CONSTRAINT CHK_TEACHERS_SALARY CHECK (SALARY > 0)
) COMMENT = 'Teacher information including contact details and employment status';

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS IDX_TEACHERS_EMAIL ON TEACHERS(EMAIL);
CREATE INDEX IF NOT EXISTS IDX_TEACHERS_SUBJECT ON TEACHERS(SUBJECT);
CREATE INDEX IF NOT EXISTS IDX_TEACHERS_DEPARTMENT ON TEACHERS(DEPARTMENT);
CREATE INDEX IF NOT EXISTS IDX_TEACHERS_STATUS ON TEACHERS(STATUS);

-- Grant permissions to roles
GRANT SELECT ON TABLE TEACHERS TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE TEACHERS TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;