!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use CURATED schema
USE SCHEMA CURATED;

-- Create stored procedure for promoting staging data to curated
CREATE OR REPLACE PROCEDURE SP_PROMOTE_TO_CURATED()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    LET RESULT STRING := '';
    LET CUSTOMER_COUNT NUMBER := 0;
    LET ORDER_COUNT NUMBER := 0;
    
    -- Promote customer data from staging to curated
    MERGE INTO CUSTOMERS AS TARGET
    USING (
        SELECT 
            CUSTOMER_ID,
            CUSTOMER_KEY,
            FIRST_NAME,
            LAST_NAME,
            FULL_NAME,
            EMAIL,
            EMAIL_DOMAIN,
            PHONE_CLEANED AS PHONE,
            ADDRESS,
            CITY,
            STATE,
            COUNTRY,
            POSTAL_CODE,
            CUSTOMER_SEGMENT,
            CASE 
                WHEN CUSTOMER_AGE_DAYS <= 90 THEN 'BRONZE'
                WHEN CUSTOMER_AGE_DAYS <= 365 THEN 'SILVER'
                WHEN CUSTOMER_AGE_DAYS <= 1095 THEN 'GOLD'
                ELSE 'PLATINUM'
            END AS CUSTOMER_TIER,
            REGISTRATION_DATE,
            CUSTOMER_AGE_DAYS,
            IS_ACTIVE,
            CURRENT_TIMESTAMP() AS UPDATED_TIMESTAMP
        FROM STAGING.STG_CUSTOMERS
        WHERE DATA_QUALITY_SCORE >= 0.7 -- Only promote high quality records
    ) AS SOURCE ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID
    WHEN MATCHED THEN
        UPDATE SET
            CUSTOMER_KEY = SOURCE.CUSTOMER_KEY,
            FIRST_NAME = SOURCE.FIRST_NAME,
            LAST_NAME = SOURCE.LAST_NAME,
            FULL_NAME = SOURCE.FULL_NAME,
            EMAIL = SOURCE.EMAIL,
            EMAIL_DOMAIN = SOURCE.EMAIL_DOMAIN,
            PHONE = SOURCE.PHONE,
            ADDRESS = SOURCE.ADDRESS,
            CITY = SOURCE.CITY,
            STATE = SOURCE.STATE,
            COUNTRY = SOURCE.COUNTRY,
            POSTAL_CODE = SOURCE.POSTAL_CODE,
            CUSTOMER_SEGMENT = SOURCE.CUSTOMER_SEGMENT,
            CUSTOMER_TIER = SOURCE.CUSTOMER_TIER,
            CUSTOMER_AGE_DAYS = SOURCE.CUSTOMER_AGE_DAYS,
            IS_ACTIVE = SOURCE.IS_ACTIVE,
            UPDATED_TIMESTAMP = SOURCE.UPDATED_TIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            CUSTOMER_ID, CUSTOMER_KEY, FIRST_NAME, LAST_NAME, FULL_NAME,
            EMAIL, EMAIL_DOMAIN, PHONE, ADDRESS, CITY, STATE, COUNTRY,
            POSTAL_CODE, CUSTOMER_SEGMENT, CUSTOMER_TIER, REGISTRATION_DATE,
            CUSTOMER_AGE_DAYS, IS_ACTIVE, UPDATED_TIMESTAMP
        ) VALUES (
            SOURCE.CUSTOMER_ID, SOURCE.CUSTOMER_KEY, SOURCE.FIRST_NAME, 
            SOURCE.LAST_NAME, SOURCE.FULL_NAME, SOURCE.EMAIL, SOURCE.EMAIL_DOMAIN,
            SOURCE.PHONE, SOURCE.ADDRESS, SOURCE.CITY, SOURCE.STATE, SOURCE.COUNTRY,
            SOURCE.POSTAL_CODE, SOURCE.CUSTOMER_SEGMENT, SOURCE.CUSTOMER_TIER, 
            SOURCE.REGISTRATION_DATE, SOURCE.CUSTOMER_AGE_DAYS, SOURCE.IS_ACTIVE,
            SOURCE.UPDATED_TIMESTAMP
        );
    
    SET CUSTOMER_COUNT = (SELECT COUNT(*) FROM CUSTOMERS);
    SET ORDER_COUNT = (SELECT COUNT(*) FROM ORDERS);
    
    SET RESULT = 'Successfully promoted data to curated: ' || :CUSTOMER_COUNT || ' customers, ' || :ORDER_COUNT || ' orders';
    
    RETURN :RESULT;
END;
$$
COMMENT = 'Promote high-quality staging data to curated layer';
