!set variable_substitution=true;

-- Set context using environment variables
USE ROLE &SNOWSQL_ENVVAR_ROLE;

-- Create FAMILYBUSINESS database if not exists
CREATE DATABASE IF NOT EXISTS FAMILYBUSINESS
    COMMENT = 'Family business database for multi-layered data architecture (RAW, STAGING, CURATED)';

-- Use the FAMILYBUSINESS database
USE DATABASE FAMILYBUSINESS;

-- Create RAW schema for source data ingestion
CREATE SCHEMA IF NOT EXISTS RAW
    COMMENT = 'Raw data schema for ingested source data without transformation';

-- Create STAGING schema for data cleansing and quality checks
CREATE SCHEMA IF NOT EXISTS STAGING
    COMMENT = 'Staging schema for data cleansing, validation, and quality checks';

-- Create CURATED schema for business-ready data
CREATE SCHEMA IF NOT EXISTS CURATED
    COMMENT = 'Curated schema for business-ready, high-quality data';

-- Create default PUBLIC schema
CREATE SCHEMA IF NOT EXISTS PUBLIC
    COMMENT = 'Default public schema for family business objects';

-- Grant database permissions to the current role
GRANT ALL ON DATABASE FAMILYBUSINESS TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant schema permissions
GRANT ALL ON SCHEMA FAMILYBUSINESS.RAW TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON SCHEMA FAMILYBUSINESS.STAGING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON SCHEMA FAMILYBUSINESS.CURATED TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON SCHEMA FAMILYBUSINESS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant current object permissions for RAW schema
GRANT ALL ON ALL TABLES IN SCHEMA FAMILYBUSINESS.RAW TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA FAMILYBUSINESS.RAW TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL PROCEDURES IN SCHEMA FAMILYBUSINESS.RAW TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA FAMILYBUSINESS.RAW TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL FILE FORMATS IN SCHEMA FAMILYBUSINESS.RAW TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL STAGES IN SCHEMA FAMILYBUSINESS.RAW TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant current object permissions for STAGING schema
GRANT ALL ON ALL TABLES IN SCHEMA FAMILYBUSINESS.STAGING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA FAMILYBUSINESS.STAGING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL PROCEDURES IN SCHEMA FAMILYBUSINESS.STAGING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA FAMILYBUSINESS.STAGING TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant current object permissions for CURATED schema
GRANT ALL ON ALL TABLES IN SCHEMA FAMILYBUSINESS.CURATED TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA FAMILYBUSINESS.CURATED TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL PROCEDURES IN SCHEMA FAMILYBUSINESS.CURATED TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA FAMILYBUSINESS.CURATED TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant current object permissions for PUBLIC schema
GRANT ALL ON ALL TABLES IN SCHEMA FAMILYBUSINESS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA FAMILYBUSINESS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL PROCEDURES IN SCHEMA FAMILYBUSINESS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA FAMILYBUSINESS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant future object permissions for RAW schema
GRANT ALL ON FUTURE TABLES IN SCHEMA FAMILYBUSINESS.RAW TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA FAMILYBUSINESS.RAW TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA FAMILYBUSINESS.RAW TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA FAMILYBUSINESS.RAW TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA FAMILYBUSINESS.RAW TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE STAGES IN SCHEMA FAMILYBUSINESS.RAW TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant future object permissions for STAGING schema
GRANT ALL ON FUTURE TABLES IN SCHEMA FAMILYBUSINESS.STAGING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA FAMILYBUSINESS.STAGING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA FAMILYBUSINESS.STAGING TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA FAMILYBUSINESS.STAGING TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant future object permissions for CURATED schema
GRANT ALL ON FUTURE TABLES IN SCHEMA FAMILYBUSINESS.CURATED TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA FAMILYBUSINESS.CURATED TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA FAMILYBUSINESS.CURATED TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA FAMILYBUSINESS.CURATED TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant future object permissions for PUBLIC schema
GRANT ALL ON FUTURE TABLES IN SCHEMA FAMILYBUSINESS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA FAMILYBUSINESS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA FAMILYBUSINESS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT ALL ON FUTURE FUNCTIONS IN SCHEMA FAMILYBUSINESS.PUBLIC TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Set default schema for convenience
USE SCHEMA FAMILYBUSINESS.CURATED;