-- Change History Information
-- VERSION:      1.0.5
-- DESCRIPTION:  Create automated tasks for school business operations
-- CREATED:      2024-09-24
-- AUTHOR:       School Business Team
-- DEPENDENCIES: All previous files (tables, views, procedures)
-- ENVIRONMENT:  ALL (DEV, QA, PROD)

!set variable_substitution=true;

USE ROLE SYSADMIN;
USE DATABASE SCHOOL_BUSINESS_DB;
USE SCHEMA SCHOOL_BUSINESS_SCHEMA;

-- Create system log table for task monitoring and general logging
CREATE TABLE IF NOT EXISTS SYSTEM_LOG (
    LOG_ID INT AUTOINCREMENT PRIMARY KEY,
    LOG_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LOG_LEVEL VARCHAR(10) DEFAULT 'INFO' CHECK (LOG_LEVEL IN ('INFO', 'WARN', 'ERROR', 'DEBUG')),
    LOG_SOURCE VARCHAR(50),
    LOG_MESSAGE VARCHAR(1000),
    ADDITIONAL_DATA VARIANT
) COMMENT = 'System logging table for tracking automated tasks and operations';

-- Create enrollment statistics table for historical tracking
CREATE TABLE IF NOT EXISTS ENROLLMENT_STATS_HISTORY (
    STATS_ID INT AUTOINCREMENT PRIMARY KEY,
    STATS_DATE DATE,
    TOTAL_STUDENTS INT,
    ACTIVE_STUDENTS INT,
    TOTAL_TEACHERS INT,
    ACTIVE_TEACHERS INT,
    TOTAL_COURSES INT,
    ACTIVE_COURSES INT,
    TOTAL_ENROLLMENTS INT,
    ACTIVE_ENROLLMENTS INT,
    COMPLETED_ENROLLMENTS INT,
    AVERAGE_GPA DECIMAL(3,2),
    AVERAGE_ATTENDANCE DECIMAL(5,2),
    DROP_RATE_PERCENTAGE DECIMAL(5,2),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Historical tracking of daily enrollment and academic statistics';

-- Task to update enrollment statistics daily
CREATE OR REPLACE TASK TSK_UPDATE_ENROLLMENT_STATS
    WAREHOUSE = SCHOOL_BUSINESS_WH
    SCHEDULE = 'USING CRON 0 6 * * * UTC'  -- Daily at 6 AM UTC
    COMMENT = 'Daily task to calculate and store enrollment statistics'
AS
BEGIN
    -- Calculate and insert daily statistics
    INSERT INTO ENROLLMENT_STATS_HISTORY (
        STATS_DATE, TOTAL_STUDENTS, ACTIVE_STUDENTS, TOTAL_TEACHERS, ACTIVE_TEACHERS,
        TOTAL_COURSES, ACTIVE_COURSES, TOTAL_ENROLLMENTS, ACTIVE_ENROLLMENTS,
        COMPLETED_ENROLLMENTS, AVERAGE_GPA, AVERAGE_ATTENDANCE, DROP_RATE_PERCENTAGE
    )
    SELECT 
        CURRENT_DATE() AS STATS_DATE,
        (SELECT COUNT(*) FROM STUDENTS) AS TOTAL_STUDENTS,
        (SELECT COUNT(*) FROM STUDENTS WHERE STATUS = 'ACTIVE') AS ACTIVE_STUDENTS,
        (SELECT COUNT(*) FROM TEACHERS) AS TOTAL_TEACHERS,
        (SELECT COUNT(*) FROM TEACHERS WHERE STATUS = 'ACTIVE') AS ACTIVE_TEACHERS,
        (SELECT COUNT(*) FROM COURSES) AS TOTAL_COURSES,
        (SELECT COUNT(*) FROM COURSES WHERE STATUS = 'ACTIVE') AS ACTIVE_COURSES,
        (SELECT COUNT(*) FROM ENROLLMENTS) AS TOTAL_ENROLLMENTS,
        (SELECT COUNT(*) FROM ENROLLMENTS WHERE STATUS = 'ACTIVE') AS ACTIVE_ENROLLMENTS,
        (SELECT COUNT(*) FROM ENROLLMENTS WHERE STATUS = 'COMPLETED') AS COMPLETED_ENROLLMENTS,
        (SELECT ROUND(AVG(GRADE), 2) FROM ENROLLMENTS WHERE GRADE IS NOT NULL) AS AVERAGE_GPA,
        (SELECT ROUND(AVG(ATTENDANCE_PERCENTAGE), 2) FROM ENROLLMENTS WHERE ATTENDANCE_PERCENTAGE IS NOT NULL) AS AVERAGE_ATTENDANCE,
        (SELECT ROUND((COUNT(CASE WHEN STATUS = 'DROPPED' THEN 1 END) * 100.0 / COUNT(*)), 2) FROM ENROLLMENTS) AS DROP_RATE_PERCENTAGE;
    
    -- Log the successful update
    INSERT INTO SYSTEM_LOG (LOG_LEVEL, LOG_SOURCE, LOG_MESSAGE)
    VALUES ('INFO', 'TSK_UPDATE_ENROLLMENT_STATS', 'Daily enrollment statistics updated successfully for ' || CURRENT_DATE());
    
EXCEPTION
    WHEN OTHER THEN
        -- Log any errors
        INSERT INTO SYSTEM_LOG (LOG_LEVEL, LOG_SOURCE, LOG_MESSAGE, ADDITIONAL_DATA)
        VALUES ('ERROR', 'TSK_UPDATE_ENROLLMENT_STATS', 'Failed to update enrollment statistics: ' || SQLERRM, 
                OBJECT_CONSTRUCT('error_code', SQLCODE, 'error_state', SQLSTATE));
END;

-- Task to send attendance alerts for students with low attendance
CREATE OR REPLACE TASK TSK_ATTENDANCE_ALERTS
    WAREHOUSE = SCHOOL_BUSINESS_WH
    SCHEDULE = 'USING CRON 0 8 * * 1 UTC'  -- Weekly on Monday at 8 AM UTC
    COMMENT = 'Weekly task to identify and log students with attendance issues'
AS
BEGIN
    -- Create a temporary table for low attendance students
    CREATE OR REPLACE TEMPORARY TABLE TEMP_LOW_ATTENDANCE AS
    SELECT 
        s.STUDENT_ID,
        s.FIRST_NAME || ' ' || s.LAST_NAME AS STUDENT_NAME,
        s.EMAIL,
        c.COURSE_CODE,
        c.COURSE_NAME,
        e.ATTENDANCE_PERCENTAGE,
        t.FIRST_NAME || ' ' || t.LAST_NAME AS INSTRUCTOR_NAME,
        t.EMAIL AS INSTRUCTOR_EMAIL
    FROM ENROLLMENTS e
    JOIN STUDENTS s ON e.STUDENT_ID = s.STUDENT_ID
    JOIN COURSES c ON e.COURSE_ID = c.COURSE_ID
    LEFT JOIN TEACHERS t ON c.TEACHER_ID = t.TEACHER_ID
    WHERE e.STATUS = 'ACTIVE' 
    AND e.ATTENDANCE_PERCENTAGE IS NOT NULL 
    AND e.ATTENDANCE_PERCENTAGE < 75.0;
    
    -- Log attendance alerts
    INSERT INTO SYSTEM_LOG (LOG_LEVEL, LOG_SOURCE, LOG_MESSAGE, ADDITIONAL_DATA)
    SELECT 
        'WARN' AS LOG_LEVEL,
        'TSK_ATTENDANCE_ALERTS' AS LOG_SOURCE,
        'Low attendance alert: ' || STUDENT_NAME || ' in ' || COURSE_NAME || ' (' || ATTENDANCE_PERCENTAGE || '% attendance)' AS LOG_MESSAGE,
        OBJECT_CONSTRUCT(
            'student_id', STUDENT_ID,
            'student_email', EMAIL,
            'course_code', COURSE_CODE,
            'attendance_percentage', ATTENDANCE_PERCENTAGE,
            'instructor_email', INSTRUCTOR_EMAIL
        ) AS ADDITIONAL_DATA
    FROM TEMP_LOW_ATTENDANCE;
    
    -- Summary log entry
    INSERT INTO SYSTEM_LOG (LOG_LEVEL, LOG_SOURCE, LOG_MESSAGE, ADDITIONAL_DATA)
    SELECT 
        'INFO' AS LOG_LEVEL,
        'TSK_ATTENDANCE_ALERTS' AS LOG_SOURCE,
        'Weekly attendance check completed. Found ' || COUNT(*) || ' students with low attendance.' AS LOG_MESSAGE,
        OBJECT_CONSTRUCT('low_attendance_count', COUNT(*), 'check_date', CURRENT_DATE()) AS ADDITIONAL_DATA
    FROM TEMP_LOW_ATTENDANCE;
    
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO SYSTEM_LOG (LOG_LEVEL, LOG_SOURCE, LOG_MESSAGE, ADDITIONAL_DATA)
        VALUES ('ERROR', 'TSK_ATTENDANCE_ALERTS', 'Failed to process attendance alerts: ' || SQLERRM,
                OBJECT_CONSTRUCT('error_code', SQLCODE, 'error_state', SQLSTATE));
END;

-- Task to update student status based on graduation criteria
CREATE OR REPLACE TASK TSK_UPDATE_GRADUATION_STATUS
    WAREHOUSE = SCHOOL_BUSINESS_WH
    SCHEDULE = 'USING CRON 0 9 1 * * UTC'  -- Monthly on the 1st at 9 AM UTC
    COMMENT = 'Monthly task to evaluate and update student graduation status'
AS
BEGIN
    -- Update students to graduated status if they meet criteria (120+ credits with GPA >= 2.0)
    UPDATE STUDENTS 
    SET STATUS = 'GRADUATED',
        UPDATED_AT = CURRENT_TIMESTAMP()
    WHERE STUDENT_ID IN (
        SELECT s.STUDENT_ID
        FROM STUDENTS s
        JOIN (
            SELECT 
                e.STUDENT_ID,
                SUM(CASE WHEN e.STATUS = 'COMPLETED' AND e.GRADE >= 1.0 THEN c.CREDITS ELSE 0 END) AS TOTAL_CREDITS_EARNED,
                ROUND(AVG(CASE WHEN e.GRADE IS NOT NULL THEN e.GRADE ELSE 0 END), 2) AS CUMULATIVE_GPA
            FROM ENROLLMENTS e
            JOIN COURSES c ON e.COURSE_ID = c.COURSE_ID
            GROUP BY e.STUDENT_ID
            HAVING TOTAL_CREDITS_EARNED >= 120 AND CUMULATIVE_GPA >= 2.0
        ) gpa_calc ON s.STUDENT_ID = gpa_calc.STUDENT_ID
        WHERE s.STATUS = 'ACTIVE'
    );
    
    -- Log the graduation updates
    INSERT INTO SYSTEM_LOG (LOG_LEVEL, LOG_SOURCE, LOG_MESSAGE, ADDITIONAL_DATA)
    VALUES ('INFO', 'TSK_UPDATE_GRADUATION_STATUS', 
            'Monthly graduation status update completed. Updated ' || SQL%ROWCOUNT || ' students to GRADUATED status.',
            OBJECT_CONSTRUCT('students_graduated', SQL%ROWCOUNT, 'update_date', CURRENT_DATE()));
    
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO SYSTEM_LOG (LOG_LEVEL, LOG_SOURCE, LOG_MESSAGE, ADDITIONAL_DATA)
        VALUES ('ERROR', 'TSK_UPDATE_GRADUATION_STATUS', 'Failed to update graduation status: ' || SQLERRM,
                OBJECT_CONSTRUCT('error_code', SQLCODE, 'error_state', SQLSTATE));
END;

-- Task to clean up old log entries (keep only last 90 days)
CREATE OR REPLACE TASK TSK_CLEANUP_LOGS
    WAREHOUSE = SCHOOL_BUSINESS_WH
    SCHEDULE = 'USING CRON 0 2 * * * UTC'  -- Daily at 2 AM UTC
    COMMENT = 'Daily cleanup of old system log entries'
AS
BEGIN
    -- Delete logs older than 90 days
    DELETE FROM SYSTEM_LOG 
    WHERE LOG_DATE < DATEADD(DAY, -90, CURRENT_DATE());
    
    -- Log the cleanup
    INSERT INTO SYSTEM_LOG (LOG_LEVEL, LOG_SOURCE, LOG_MESSAGE, ADDITIONAL_DATA)
    VALUES ('INFO', 'TSK_CLEANUP_LOGS', 
            'Log cleanup completed. Removed ' || SQL%ROWCOUNT || ' old log entries.',
            OBJECT_CONSTRUCT('deleted_logs', SQL%ROWCOUNT, 'cleanup_date', CURRENT_DATE()));
            
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO SYSTEM_LOG (LOG_LEVEL, LOG_SOURCE, LOG_MESSAGE, ADDITIONAL_DATA)
        VALUES ('ERROR', 'TSK_CLEANUP_LOGS', 'Failed to cleanup logs: ' || SQLERRM,
                OBJECT_CONSTRUCT('error_code', SQLCODE, 'error_state', SQLSTATE));
END;

-- Task to generate weekly academic performance reports
CREATE OR REPLACE TASK TSK_WEEKLY_PERFORMANCE_REPORT
    WAREHOUSE = SCHOOL_BUSINESS_WH
    SCHEDULE = 'USING CRON 0 10 * * 0 UTC'  -- Weekly on Sunday at 10 AM UTC
    COMMENT = 'Weekly task to generate and log academic performance summary'
AS
BEGIN
    -- Log weekly performance summary
    INSERT INTO SYSTEM_LOG (LOG_LEVEL, LOG_SOURCE, LOG_MESSAGE, ADDITIONAL_DATA)
    SELECT 
        'INFO' AS LOG_LEVEL,
        'TSK_WEEKLY_PERFORMANCE_REPORT' AS LOG_SOURCE,
        'Weekly Performance Report Generated' AS LOG_MESSAGE,
        OBJECT_CONSTRUCT(
            'report_date', CURRENT_DATE(),
            'total_active_students', COUNT(DISTINCT s.STUDENT_ID),
            'total_active_courses', COUNT(DISTINCT c.COURSE_ID),
            'average_gpa', ROUND(AVG(e.GRADE), 2),
            'average_attendance', ROUND(AVG(e.ATTENDANCE_PERCENTAGE), 2),
            'students_on_probation', COUNT(DISTINCT CASE WHEN gpa_calc.CUMULATIVE_GPA < 2.0 THEN s.STUDENT_ID END)
        ) AS ADDITIONAL_DATA
    FROM STUDENTS s
    LEFT JOIN ENROLLMENTS e ON s.STUDENT_ID = e.STUDENT_ID AND e.STATUS IN ('ACTIVE', 'COMPLETED')
    LEFT JOIN COURSES c ON e.COURSE_ID = c.COURSE_ID AND c.STATUS = 'ACTIVE'
    LEFT JOIN (
        SELECT 
            e2.STUDENT_ID,
            ROUND(AVG(e2.GRADE), 2) AS CUMULATIVE_GPA
        FROM ENROLLMENTS e2
        WHERE e2.GRADE IS NOT NULL
        GROUP BY e2.STUDENT_ID
    ) gpa_calc ON s.STUDENT_ID = gpa_calc.STUDENT_ID
    WHERE s.STATUS = 'ACTIVE';
    
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO SYSTEM_LOG (LOG_LEVEL, LOG_SOURCE, LOG_MESSAGE, ADDITIONAL_DATA)
        VALUES ('ERROR', 'TSK_WEEKLY_PERFORMANCE_REPORT', 'Failed to generate weekly report: ' || SQLERRM,
                OBJECT_CONSTRUCT('error_code', SQLCODE, 'error_state', SQLSTATE));
END;

-- Grant permissions on new tables
GRANT SELECT ON TABLE SYSTEM_LOG TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SYSTEM_LOG TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

GRANT SELECT ON TABLE ENROLLMENT_STATS_HISTORY TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ENROLLMENT_STATS_HISTORY TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

-- Grant task permissions (tasks need to be manually resumed after creation)
GRANT OPERATE ON ALL TASKS IN SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;
GRANT MONITOR ON ALL TASKS IN SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT MONITOR ON ALL TASKS IN SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

-- Note: Tasks are created in SUSPENDED state and need to be manually resumed
-- To activate the tasks, run these commands after deployment:
-- ALTER TASK TSK_UPDATE_ENROLLMENT_STATS RESUME;
-- ALTER TASK TSK_ATTENDANCE_ALERTS RESUME;
-- ALTER TASK TSK_UPDATE_GRADUATION_STATUS RESUME;
-- ALTER TASK TSK_CLEANUP_LOGS RESUME;
-- ALTER TASK TSK_WEEKLY_PERFORMANCE_REPORT RESUME;