!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use REPORTING schema
USE SCHEMA REPORTING;

-- Create customer insights view
CREATE OR REPLACE VIEW VW_CUSTOMER_INSIGHTS AS
WITH CUSTOMER_METRICS AS (
    SELECT 
        CUSTOMER_ID,
        CUSTOMER_SEGMENT,
        MAX(REPORT_PERIOD) AS LATEST_PERIOD,
        SUM(TOTAL_ORDERS) AS TOTAL_ORDERS,
        SUM(TOTAL_SPEND) AS TOTAL_SPEND,
        AVG(AVERAGE_ORDER_VALUE) AS AVG_ORDER_VALUE,
        MIN(DAYS_SINCE_LAST_ORDER) AS DAYS_SINCE_LAST_ORDER,
        MAX(LIFETIME_VALUE) AS LIFETIME_VALUE
    FROM RPT_CUSTOMER_PERFORMANCE
    GROUP BY CUSTOMER_ID, CUSTOMER_SEGMENT
)
SELECT 
    CUSTOMER_ID,
    CUSTOMER_SEGMENT,
    LATEST_PERIOD,
    TOTAL_ORDERS,
    TOTAL_SPEND,
    AVG_ORDER_VALUE,
    DAYS_SINCE_LAST_ORDER,
    LIFETIME_VALUE,
    CASE 
        WHEN DAYS_SINCE_LAST_ORDER <= 30 THEN 'ACTIVE'
        WHEN DAYS_SINCE_LAST_ORDER <= 90 THEN 'AT_RISK'
        WHEN DAYS_SINCE_LAST_ORDER <= 180 THEN 'DORMANT'
        ELSE 'INACTIVE'
    END AS CUSTOMER_STATUS,
    CASE 
        WHEN LIFETIME_VALUE >= 10000 THEN 'VIP'
        WHEN LIFETIME_VALUE >= 5000 THEN 'HIGH_VALUE'
        WHEN LIFETIME_VALUE >= 1000 THEN 'MEDIUM_VALUE'
        ELSE 'LOW_VALUE'
    END AS VALUE_TIER
FROM CUSTOMER_METRICS
COMMENT = 'Customer insights and segmentation view';