!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use REPORTING schema
USE SCHEMA REPORTING;

-- Create quarterly performance view
CREATE OR REPLACE VIEW VW_QUARTERLY_PERFORMANCE AS
WITH QUARTERLY_DATA AS (
    SELECT 
        LEFT(YEAR_MONTH, 4) AS YEAR,
        CASE 
            WHEN RIGHT(YEAR_MONTH, 2) IN ('01', '02', '03') THEN 'Q1'
            WHEN RIGHT(YEAR_MONTH, 2) IN ('04', '05', '06') THEN 'Q2'
            WHEN RIGHT(YEAR_MONTH, 2) IN ('07', '08', '09') THEN 'Q3'
            ELSE 'Q4'
        END AS QUARTER,
        SALES_CHANNEL,
        REGION,
        SUM(TOTAL_ORDERS) AS QUARTERLY_ORDERS,
        SUM(TOTAL_CUSTOMERS) AS QUARTERLY_CUSTOMERS,
        SUM(TOTAL_REVENUE) AS QUARTERLY_REVENUE,
        SUM(TOTAL_QUANTITY) AS QUARTERLY_QUANTITY,
        AVG(AVG_ORDER_VALUE) AS AVG_QUARTERLY_ORDER_VALUE
    FROM RPT_MONTHLY_SALES
    GROUP BY 1, 2, 3, 4
)
SELECT 
    YEAR || '-' || QUARTER AS YEAR_QUARTER,
    SALES_CHANNEL,
    REGION,
    QUARTERLY_ORDERS,
    QUARTERLY_CUSTOMERS,
    QUARTERLY_REVENUE,
    QUARTERLY_QUANTITY,
    AVG_QUARTERLY_ORDER_VALUE,
    ROUND(QUARTERLY_REVENUE / NULLIF(QUARTERLY_ORDERS, 0), 2) AS REVENUE_PER_ORDER,
    ROUND(QUARTERLY_REVENUE / NULLIF(QUARTERLY_CUSTOMERS, 0), 2) AS REVENUE_PER_CUSTOMER
FROM QUARTERLY_DATA
ORDER BY YEAR, QUARTER, SALES_CHANNEL, REGION
COMMENT = 'Quarterly performance summary view for executive reporting';