!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use REPORTING schema
USE SCHEMA REPORTING;

-- Create stored procedure for generating monthly reports
CREATE OR REPLACE PROCEDURE SP_GENERATE_MONTHLY_REPORTS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    LET RESULT STRING := '';
    LET START_TIME TIMESTAMP := CURRENT_TIMESTAMP();
    LET PROCESSED_COUNT NUMBER := 0;
    
    -- Generate monthly sales report for previous month
    INSERT INTO RPT_MONTHLY_SALES (
        YEAR_MONTH,
        SALES_CHANNEL,
        REGION,
        TOTAL_ORDERS,
        TOTAL_CUSTOMERS,
        TOTAL_REVENUE,
        TOTAL_QUANTITY,
        AVG_ORDER_VALUE,
        DISCOUNT_PERCENTAGE
    )
    SELECT 
        TO_VARCHAR(DATE_TRUNC('month', DATEADD('month', -1, CURRENT_DATE())), 'YYYY-MM') AS YEAR_MONTH,
        SALES_CHANNEL,
        REGION,
        COUNT(SALES_ID) AS TOTAL_ORDERS,
        COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,
        SUM(NET_AMOUNT) AS TOTAL_REVENUE,
        SUM(QUANTITY) AS TOTAL_QUANTITY,
        AVG(TOTAL_AMOUNT) AS AVG_ORDER_VALUE,
        ROUND((SUM(DISCOUNT_AMOUNT) / NULLIF(SUM(TOTAL_AMOUNT), 0)) * 100, 2) AS DISCOUNT_PERCENTAGE
    FROM ANALYTICS.FACT_SALES
    WHERE DATE_TRUNC('month', ORDER_DATE) = DATE_TRUNC('month', DATEADD('month', -1, CURRENT_DATE()))
    GROUP BY YEAR_MONTH, SALES_CHANNEL, REGION;
    
    SET PROCESSED_COUNT = (SELECT COUNT(*) FROM RPT_MONTHLY_SALES WHERE YEAR_MONTH = TO_VARCHAR(DATE_TRUNC('month', DATEADD('month', -1, CURRENT_DATE())), 'YYYY-MM'));
    
    LET END_TIME TIMESTAMP := CURRENT_TIMESTAMP();
    LET EXECUTION_TIME NUMBER := DATEDIFF('second', :START_TIME, :END_TIME);
    
    SET RESULT = 'Monthly reports generated successfully. Processed ' || :PROCESSED_COUNT || ' records in ' || :EXECUTION_TIME || ' seconds';
    
    RETURN :RESULT;
END;
$$
COMMENT = 'Stored procedure to generate monthly sales and performance reports';

-- Grant execution permissions to appropriate roles
GRANT USAGE ON PROCEDURE SP_GENERATE_MONTHLY_REPORTS() TO ROLE &SNOWSQL_ENVVAR_ROLE;