-- Change History Information
-- VERSION:      1.0.0
-- DESCRIPTION:  School Business Database setup - roles, users, database, and warehouse
-- CREATED:      2024-09-24
-- AUTHOR:       School Business Team
-- DEPENDENCIES: None
-- ENVIRONMENT:  ALL (DEV, QA, PROD)

!set variable_substitution=true;

-- Switch to ACCOUNTADMIN for user and role creation
USE ROLE ACCOUNTADMIN;

-- Create custom roles first
CREATE ROLE IF NOT EXISTS SCHOOL_BUSINESS_DB_READ_ROLE
    COMMENT = 'Read-only role for School Business Database';
    
CREATE ROLE IF NOT EXISTS SCHOOL_BUSINESS_DB_READ_WRITE_ROLE
    COMMENT = 'Read-write role for School Business Database';

-- Grant custom roles to SYSADMIN (best practice)
GRANT ROLE SCHOOL_BUSINESS_DB_READ_ROLE TO ROLE SYSADMIN;
GRANT ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE TO ROLE SYSADMIN;

-- Switch to SYSADMIN for database and warehouse creation
USE ROLE SYSADMIN;

-- Create database with environment-specific naming if needed
CREATE DATABASE IF NOT EXISTS SCHOOL_BUSINESS_DB
    COMMENT = 'Database for school business operations';
    
USE DATABASE SCHOOL_BUSINESS_DB;

CREATE SCHEMA IF NOT EXISTS SCHOOL_BUSINESS_SCHEMA
    COMMENT = 'Main schema for school business data';

-- Create a warehouse for the school business operations
CREATE WAREHOUSE IF NOT EXISTS SCHOOL_BUSINESS_WH WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for school business operations';

-- Switch back to ACCOUNTADMIN for user creation
USE ROLE ACCOUNTADMIN;

-- Create users with strong passwords (change in production)
CREATE USER IF NOT EXISTS SCHOOL_BUSINESS_DB_READ_USER 
    PASSWORD = 'ReadUserPass123!' 
    DEFAULT_ROLE = SCHOOL_BUSINESS_DB_READ_ROLE 
    DEFAULT_WAREHOUSE = SCHOOL_BUSINESS_WH
    DEFAULT_NAMESPACE = 'SCHOOL_BUSINESS_DB.SCHOOL_BUSINESS_SCHEMA'
    MUST_CHANGE_PASSWORD = TRUE
    COMMENT = 'Read-only user for School Business Database';
    
CREATE USER IF NOT EXISTS SCHOOL_BUSINESS_DB_READ_WRITE_USER 
    PASSWORD = 'ReadWriteUserPass123!' 
    DEFAULT_ROLE = SCHOOL_BUSINESS_DB_READ_WRITE_ROLE 
    DEFAULT_WAREHOUSE = SCHOOL_BUSINESS_WH
    DEFAULT_NAMESPACE = 'SCHOOL_BUSINESS_DB.SCHOOL_BUSINESS_SCHEMA'
    MUST_CHANGE_PASSWORD = TRUE
    COMMENT = 'Read-write user for School Business Database';

-- Grant roles to users
GRANT ROLE SCHOOL_BUSINESS_DB_READ_ROLE TO USER SCHOOL_BUSINESS_DB_READ_USER;
GRANT ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE TO USER SCHOOL_BUSINESS_DB_READ_WRITE_USER;

-- Grant read role to read-write role (hierarchical access)
GRANT ROLE SCHOOL_BUSINESS_DB_READ_ROLE TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

-- Set context for permission grants
USE ROLE SYSADMIN;
USE DATABASE SCHOOL_BUSINESS_DB;
USE SCHEMA SCHOOL_BUSINESS_SCHEMA;

-- Grant database and warehouse permissions
GRANT USAGE ON DATABASE SCHOOL_BUSINESS_DB TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT USAGE ON DATABASE SCHOOL_BUSINESS_DB TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

GRANT USAGE ON WAREHOUSE SCHOOL_BUSINESS_WH TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT USAGE ON WAREHOUSE SCHOOL_BUSINESS_WH TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

GRANT OPERATE ON WAREHOUSE SCHOOL_BUSINESS_WH TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT OPERATE ON WAREHOUSE SCHOOL_BUSINESS_WH TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

-- Grant schema permissions
GRANT USAGE ON SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_ROLE;
GRANT USAGE ON SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;

-- Grant schema-level permissions to READ_WRITE_ROLE
GRANT CREATE TABLE ON SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;
GRANT CREATE VIEW ON SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;
GRANT CREATE STAGE ON SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;
GRANT CREATE PIPE ON SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;
GRANT CREATE TASK ON SCHEMA SCHOOL_BUSINESS_SCHEMA TO ROLE SCHOOL_BUSINESS_DB_READ_WRITE_ROLE;