!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use STAGING schema
USE SCHEMA STAGING;

-- Create staging orders table
CREATE TABLE IF NOT EXISTS STG_ORDERS (
    ORDER_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_STATUS VARCHAR(50),
    ORDER_STATUS_STANDARDIZED VARCHAR(50),
    TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
    CURRENCY_CODE VARCHAR(3) DEFAULT 'USD',
    PAYMENT_METHOD VARCHAR(50),
    PAYMENT_METHOD_STANDARDIZED VARCHAR(50),
    SHIPPING_ADDRESS VARCHAR(500),
    BILLING_ADDRESS VARCHAR(500),
    SALES_CHANNEL VARCHAR(50),
    SALES_REP_ID NUMBER(38,0),
    REGION VARCHAR(100),
    ORDER_YEAR NUMBER(4,0),
    ORDER_MONTH NUMBER(2,0),
    ORDER_QUARTER NUMBER(1,0),
    IS_VALID_ORDER BOOLEAN DEFAULT TRUE,
    DATA_QUALITY_SCORE NUMBER(3,2) DEFAULT 1.00,
    DATA_QUALITY_FLAGS VARCHAR(500),
    PROCESSED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR(50),
    CONSTRAINT PK_STG_ORDERS PRIMARY KEY (ORDER_ID)
)
COMMENT = 'Staging orders data with transformations and quality checks';