!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Create STAGING schema if not exists
CREATE SCHEMA IF NOT EXISTS STAGING
    COMMENT = 'Staging schema for cleaned and transformed data';

USE SCHEMA STAGING;

-- Create staging customers table with data quality checks
CREATE TABLE IF NOT EXISTS STG_CUSTOMERS (
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_KEY VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    FULL_NAME VARCHAR(200),
    EMAIL VARCHAR(255),
    EMAIL_DOMAIN VARCHAR(100),
    PHONE VARCHAR(20),
    PHONE_CLEANED VARCHAR(20),
    ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    CUSTOMER_SEGMENT VARCHAR(50),
    REGISTRATION_DATE DATE,
    CUSTOMER_AGE_DAYS NUMBER(38,0),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    DATA_QUALITY_SCORE NUMBER(3,2) DEFAULT 1.00,
    DATA_QUALITY_FLAGS VARCHAR(500),
    PROCESSED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR(50),
    CONSTRAINT PK_STG_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
)
COMMENT = 'Staging customer data with data quality enhancements';