!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Create ANALYTICS schema if not exists
CREATE SCHEMA IF NOT EXISTS ANALYTICS
    COMMENT = 'Analytics schema for dimensional tables and analytical views';

USE SCHEMA ANALYTICS;

-- Create dimension table for customer analytics
CREATE TABLE IF NOT EXISTS DIM_CUSTOMER (
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_KEY VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    CUSTOMER_SEGMENT VARCHAR(50),
    REGISTRATION_DATE DATE,
    LAST_UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
)
COMMENT = 'Customer dimension table for analytics';

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS IDX_DIM_CUSTOMER_KEY ON DIM_CUSTOMER(CUSTOMER_KEY);
CREATE INDEX IF NOT EXISTS IDX_DIM_CUSTOMER_SEGMENT ON DIM_CUSTOMER(CUSTOMER_SEGMENT);
CREATE INDEX IF NOT EXISTS IDX_DIM_CUSTOMER_EMAIL ON DIM_CUSTOMER(EMAIL);

-- Grant appropriate permissions to role
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DIM_CUSTOMER TO ROLE &SNOWSQL_ENVVAR_ROLE;