!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use ANALYTICS schema
USE SCHEMA ANALYTICS;

-- Create product dimension table
CREATE TABLE IF NOT EXISTS DIM_PRODUCT (
    PRODUCT_ID NUMBER(38,0) NOT NULL,
    PRODUCT_KEY VARCHAR(50) NOT NULL,
    PRODUCT_NAME VARCHAR(200) NOT NULL,
    PRODUCT_CATEGORY VARCHAR(100),
    PRODUCT_SUBCATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    UNIT_COST NUMBER(10,2),
    LIST_PRICE NUMBER(10,2),
    SIZE VARCHAR(50),
    COLOR VARCHAR(50),
    WEIGHT NUMBER(8,2),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE DATE DEFAULT CURRENT_DATE(),
    LAST_UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DIM_PRODUCT PRIMARY KEY (PRODUCT_ID)
)
COMMENT = 'Product dimension table for analytics';

-- Create indexes
CREATE INDEX IF NOT EXISTS IDX_DIM_PRODUCT_KEY ON DIM_PRODUCT(PRODUCT_KEY);
CREATE INDEX IF NOT EXISTS IDX_DIM_PRODUCT_CATEGORY ON DIM_PRODUCT(PRODUCT_CATEGORY);
CREATE INDEX IF NOT EXISTS IDX_DIM_PRODUCT_BRAND ON DIM_PRODUCT(BRAND);