!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use ANALYTICS schema
USE SCHEMA ANALYTICS;

-- Create fact table for sales analytics
CREATE TABLE IF NOT EXISTS FACT_SALES (
    SALES_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    PRODUCT_ID NUMBER(38,0) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    QUANTITY NUMBER(10,2) NOT NULL,
    UNIT_PRICE NUMBER(10,2) NOT NULL,
    TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
    DISCOUNT_AMOUNT NUMBER(10,2) DEFAULT 0,
    TAX_AMOUNT NUMBER(10,2) DEFAULT 0,
    NET_AMOUNT NUMBER(12,2) NOT NULL,
    SALES_CHANNEL VARCHAR(50),
    SALES_REP_ID NUMBER(38,0),
    REGION VARCHAR(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_FACT_SALES PRIMARY KEY (SALES_ID)
)
COMMENT = 'Sales fact table for analytics and reporting';

-- Create indexes for analytical queries
CREATE INDEX IF NOT EXISTS IDX_FACT_SALES_CUSTOMER ON FACT_SALES(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IDX_FACT_SALES_PRODUCT ON FACT_SALES(PRODUCT_ID);
CREATE INDEX IF NOT EXISTS IDX_FACT_SALES_DATE ON FACT_SALES(ORDER_DATE);
CREATE INDEX IF NOT EXISTS IDX_FACT_SALES_CHANNEL ON FACT_SALES(SALES_CHANNEL);