!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use REPORTING schema
USE SCHEMA REPORTING;

-- Create task for generating monthly reports
CREATE OR REPLACE TASK TASK_GENERATE_MONTHLY_REPORTS
    WAREHOUSE = &SNOWSQL_ENVVAR_WH
    SCHEDULE = 'CRON 0 2 1 * * UTC' -- Run at 2 AM on the 1st of every month
AS
$$
BEGIN
    -- Generate monthly sales report for previous month
    INSERT INTO RPT_MONTHLY_SALES (
        YEAR_MONTH,
        SALES_CHANNEL,
        REGION,
        TOTAL_ORDERS,
        TOTAL_CUSTOMERS,
        TOTAL_REVENUE,
        TOTAL_QUANTITY,
        AVG_ORDER_VALUE,
        DISCOUNT_PERCENTAGE
    )
    SELECT 
        TO_VARCHAR(DATE_TRUNC('month', DATEADD('month', -1, CURRENT_DATE())), 'YYYY-MM') AS YEAR_MONTH,
        SALES_CHANNEL,
        REGION,
        COUNT(SALES_ID) AS TOTAL_ORDERS,
        COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,
        SUM(NET_AMOUNT) AS TOTAL_REVENUE,
        SUM(QUANTITY) AS TOTAL_QUANTITY,
        AVG(TOTAL_AMOUNT) AS AVG_ORDER_VALUE,
        ROUND((SUM(DISCOUNT_AMOUNT) / NULLIF(SUM(TOTAL_AMOUNT), 0)) * 100, 2) AS DISCOUNT_PERCENTAGE
    FROM ANALYTICS.FACT_SALES
    WHERE DATE_TRUNC('month', ORDER_DATE) = DATE_TRUNC('month', DATEADD('month', -1, CURRENT_DATE()))
    GROUP BY YEAR_MONTH, SALES_CHANNEL, REGION;
END;
$$
COMMENT = 'Monthly task to generate sales reports';

-- Set task ownership and grant permissions
GRANT OWNERSHIP ON TASK TASK_GENERATE_MONTHLY_REPORTS TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT OPERATE ON TASK TASK_GENERATE_MONTHLY_REPORTS TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Start the task (commented out for initial deployment)
-- ALTER TASK TASK_GENERATE_MONTHLY_REPORTS RESUME;