!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use REPORTING schema
USE SCHEMA REPORTING;

-- Create internal stage for report exports
CREATE STAGE IF NOT EXISTS REPORTS_EXPORT_STAGE
    FILE_FORMAT = (FORMAT_NAME = 'CSV_REPORTS_FORMAT')
    DIRECTORY = (ENABLE = TRUE)
COMMENT = 'Internal stage for exporting reports to files';