!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use ANALYTICS schema
USE SCHEMA ANALYTICS;

-- Create customer sales summary view
CREATE OR REPLACE VIEW VW_CUSTOMER_SALES_SUMMARY AS
SELECT 
    DC.CUSTOMER_ID,
    DC.CUSTOMER_KEY,
    DC.FIRST_NAME,
    DC.LAST_NAME,
    DC.CUSTOMER_SEGMENT,
    COUNT(FS.SALES_ID) AS TOTAL_ORDERS,
    SUM(FS.QUANTITY) AS TOTAL_QUANTITY,
    SUM(FS.TOTAL_AMOUNT) AS TOTAL_SALES_AMOUNT,
    SUM(FS.NET_AMOUNT) AS TOTAL_NET_AMOUNT,
    AVG(FS.TOTAL_AMOUNT) AS AVG_ORDER_VALUE,
    MIN(FS.ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(FS.ORDER_DATE) AS LAST_ORDER_DATE,
    DATEDIFF('day', MIN(FS.ORDER_DATE), MAX(FS.ORDER_DATE)) AS CUSTOMER_LIFETIME_DAYS
FROM DIM_CUSTOMER DC
LEFT JOIN FACT_SALES FS ON DC.CUSTOMER_ID = FS.CUSTOMER_ID
WHERE DC.IS_ACTIVE = TRUE
GROUP BY 
    DC.CUSTOMER_ID, DC.CUSTOMER_KEY, DC.FIRST_NAME, 
    DC.LAST_NAME, DC.CUSTOMER_SEGMENT
COMMENT = 'Customer sales summary view for analytics dashboards';