!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use ANALYTICS schema
USE SCHEMA ANALYTICS;

-- Create product performance view
CREATE OR REPLACE VIEW VW_PRODUCT_PERFORMANCE AS
SELECT 
    DP.PRODUCT_ID,
    DP.PRODUCT_KEY,
    DP.PRODUCT_NAME,
    DP.PRODUCT_CATEGORY,
    DP.BRAND,
    COUNT(FS.SALES_ID) AS TOTAL_ORDERS,
    SUM(FS.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(FS.NET_AMOUNT) AS TOTAL_REVENUE,
    AVG(FS.UNIT_PRICE) AS AVG_SELLING_PRICE,
    MAX(FS.ORDER_DATE) AS LAST_SALE_DATE,
    RANK() OVER (PARTITION BY DP.PRODUCT_CATEGORY ORDER BY SUM(FS.NET_AMOUNT) DESC) AS REVENUE_RANK_IN_CATEGORY
FROM DIM_PRODUCT DP
LEFT JOIN FACT_SALES FS ON DP.PRODUCT_ID = FS.PRODUCT_ID
WHERE DP.IS_ACTIVE = TRUE
GROUP BY 
    DP.PRODUCT_ID, DP.PRODUCT_KEY, DP.PRODUCT_NAME, 
    DP.PRODUCT_CATEGORY, DP.BRAND
COMMENT = 'Product performance analytics view';