!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use CURATED schema
USE SCHEMA CURATED;

-- Create comprehensive customer 360 view
CREATE OR REPLACE VIEW VW_CUSTOMER_360 AS
WITH CUSTOMER_METRICS AS (
    SELECT 
        C.CUSTOMER_ID,
        C.CUSTOMER_KEY,
        C.FULL_NAME,
        C.EMAIL,
        C.CUSTOMER_SEGMENT,
        C.CUSTOMER_TIER,
        C.REGISTRATION_DATE,
        C.CUSTOMER_AGE_DAYS,
        C.IS_ACTIVE,
        -- Order metrics
        COUNT(O.ORDER_ID) AS TOTAL_ORDERS,
        COALESCE(SUM(O.TOTAL_AMOUNT), 0) AS LIFETIME_VALUE,
        MAX(O.ORDER_DATE) AS LAST_ORDER_DATE,
        COALESCE(AVG(O.TOTAL_AMOUNT), 0) AS AVG_ORDER_VALUE,
        -- Geographic info
        C.CITY,
        C.STATE,
        C.COUNTRY,
        -- Contact preferences
        C.PREFERRED_CHANNEL,
        C.EMAIL_DOMAIN,
        -- Calculated fields
        CASE 
            WHEN C.CUSTOMER_AGE_DAYS <= 30 THEN 'NEW'
            WHEN C.CUSTOMER_AGE_DAYS <= 365 THEN 'ACTIVE'
            WHEN C.CUSTOMER_AGE_DAYS <= 1095 THEN 'ESTABLISHED'
            ELSE 'VETERAN'
        END AS CUSTOMER_LIFECYCLE_STAGE,
        CASE 
            WHEN C.EMAIL_DOMAIN LIKE '%.edu' THEN 'EDUCATION'
            WHEN C.EMAIL_DOMAIN LIKE '%.gov' THEN 'GOVERNMENT'
            WHEN C.EMAIL_DOMAIN IN ('gmail.com', 'yahoo.com', 'outlook.com', 'hotmail.com') THEN 'PERSONAL'
            ELSE 'BUSINESS'
        END AS EMAIL_CATEGORY
    FROM CUSTOMERS C
    LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
    GROUP BY 
        C.CUSTOMER_ID, C.CUSTOMER_KEY, C.FULL_NAME, C.EMAIL,
        C.CUSTOMER_SEGMENT, C.CUSTOMER_TIER, C.REGISTRATION_DATE,
        C.CUSTOMER_AGE_DAYS, C.IS_ACTIVE, C.CITY, C.STATE,
        C.COUNTRY, C.PREFERRED_CHANNEL, C.EMAIL_DOMAIN
)
SELECT 
    CUSTOMER_ID,
    CUSTOMER_KEY,
    FULL_NAME,
    EMAIL,
    CUSTOMER_SEGMENT,
    CUSTOMER_TIER,
    CUSTOMER_LIFECYCLE_STAGE,
    EMAIL_CATEGORY,
    REGISTRATION_DATE,
    CUSTOMER_AGE_DAYS,
    TOTAL_ORDERS,
    LIFETIME_VALUE,
    LAST_ORDER_DATE,
    AVG_ORDER_VALUE,
    CITY,
    STATE,
    COUNTRY,
    PREFERRED_CHANNEL,
    IS_ACTIVE
FROM CUSTOMER_METRICS
COMMENT = 'Comprehensive 360-degree view of customer data for business users';