!set variable_substitution=true;

USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Use ANALYTICS schema
USE SCHEMA ANALYTICS;

-- Create internal stage for analytics data
CREATE STAGE IF NOT EXISTS ANALYTICS_DATA_STAGE
    FILE_FORMAT = (FORMAT_NAME = 'ANALYTICS_CSV_FORMAT')
    DIRECTORY = (ENABLE = TRUE)
COMMENT = 'Internal stage for analytics data ingestion';