-- This file handles environment setup and variable definitions
!set variable_substitution=true;

-- Switch to SYSADMIN for object creation
USE ROLE SYSADMIN;

-- Create and use database
CREATE DATABASE IF NOT EXISTS &SNOWSQL_ENVVAR_DB;
USE DATABASE &SNOWSQL_ENVVAR_DB;

-- Create schema
CREATE SCHEMA IF NOT EXISTS &SNOWSQL_ENVVAR_SCHEMA;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Create warehouse if needed
CREATE WAREHOUSE IF NOT EXISTS &SNOWSQL_ENVVAR_WH
  WITH WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

-- Switch to USERADMIN for role management
USE ROLE USERADMIN;

-- Create role if not exists
CREATE ROLE IF NOT EXISTS &SNOWSQL_ENVVAR_ROLE;

-- Switch back to SYSADMIN for grants
USE ROLE SYSADMIN;

-- Grant warehouse access
GRANT USAGE ON WAREHOUSE &SNOWSQL_ENVVAR_WH TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant database privileges
GRANT USAGE ON DATABASE &SNOWSQL_ENVVAR_DB TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant schema privileges
GRANT USAGE ON SCHEMA &SNOWSQL_ENVVAR_SCHEMA TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT CREATE TABLE ON SCHEMA &SNOWSQL_ENVVAR_SCHEMA TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA &SNOWSQL_ENVVAR_SCHEMA TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Set context for subsequent operations
USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Switch back to DEV role and set context for subsequent operations
USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;