-- This file handles environment setup and variable definitions
!set variable_substitution=true;

-- Switch to ACCOUNTADMIN to manage privileges
USE ROLE ACCOUNTADMIN;

-- Create objects if they don't exist
CREATE DATABASE IF NOT EXISTS &SNOWSQL_ENVVAR_DB;
CREATE WAREHOUSE IF NOT EXISTS &SNOWSQL_ENVVAR_WH;
CREATE ROLE IF NOT EXISTS &SNOWSQL_ENVVAR_ROLE;

-- Grant privileges
GRANT USAGE ON DATABASE &SNOWSQL_ENVVAR_DB TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT USAGE ON WAREHOUSE &SNOWSQL_ENVVAR_WH TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT CREATE SCHEMA ON DATABASE &SNOWSQL_ENVVAR_DB TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Create and grant access to schema
USE DATABASE &SNOWSQL_ENVVAR_DB;
CREATE SCHEMA IF NOT EXISTS &SNOWSQL_ENVVAR_SCHEMA;
GRANT USAGE ON SCHEMA &SNOWSQL_ENVVAR_SCHEMA TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT CREATE TABLE ON SCHEMA &SNOWSQL_ENVVAR_SCHEMA TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT INSERT ON ALL TABLES IN SCHEMA &SNOWSQL_ENVVAR_SCHEMA TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA &SNOWSQL_ENVVAR_SCHEMA TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Future grants
GRANT INSERT ON FUTURE TABLES IN SCHEMA &SNOWSQL_ENVVAR_SCHEMA TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA &SNOWSQL_ENVVAR_SCHEMA TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Switch back to DEV role and set context for subsequent operations
USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;