-- Grant access script for existing objects
!set variable_substitution=true;

-- Set context
USE ROLE SYSADMIN;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;

-- Grant access to all existing tables
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA &SNOWSQL_ENVVAR_SCHEMA TO ROLE DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA &SNOWSQL_ENVVAR_SCHEMA TO ROLE DEV_ROLE;

-- Grant specific table access
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE test_deployment TO ROLE DEV_ROLE;

-- Show grants to verify
SHOW GRANTS ON SCHEMA &SNOWSQL_ENVVAR_SCHEMA;
SHOW GRANTS ON TABLE test_deployment;