-- Environment setup and access management
!set variable_substitution=true;

-- Step 1: Create objects with SYSADMIN
USE ROLE SYSADMIN;

-- Create and configure resources
CREATE DATABASE IF NOT EXISTS &SNOWSQL_ENVVAR_DB;
CREATE SCHEMA IF NOT EXISTS &SNOWSQL_ENVVAR_DB.&SNOWSQL_ENVVAR_SCHEMA;
CREATE WAREHOUSE IF NOT EXISTS &SNOWSQL_ENVVAR_WH
  WITH WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

-- Step 2: Create role with USERADMIN
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS &SNOWSQL_ENVVAR_ROLE;

-- Step 3: Grant privileges with SYSADMIN
USE ROLE SYSADMIN;

-- Grant resource access
GRANT USAGE ON WAREHOUSE &SNOWSQL_ENVVAR_WH TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT USAGE ON DATABASE &SNOWSQL_ENVVAR_DB TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT USAGE, CREATE TABLE ON SCHEMA &SNOWSQL_ENVVAR_DB.&SNOWSQL_ENVVAR_SCHEMA TO ROLE &SNOWSQL_ENVVAR_ROLE;

-- Grant table access (both existing and future)
-- Grant on fully qualified schema name
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA &SNOWSQL_ENVVAR_DB.&SNOWSQL_ENVVAR_SCHEMA 
  TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA &SNOWSQL_ENVVAR_DB.&SNOWSQL_ENVVAR_SCHEMA 
  TO ROLE DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA &SNOWSQL_ENVVAR_DB.&SNOWSQL_ENVVAR_SCHEMA 
  TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA &SNOWSQL_ENVVAR_DB.&SNOWSQL_ENVVAR_SCHEMA 
  TO ROLE DEV_ROLE;

-- Grant on current schema context (for compatibility)
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA &SNOWSQL_ENVVAR_SCHEMA 
  TO ROLE &SNOWSQL_ENVVAR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA &SNOWSQL_ENVVAR_SCHEMA 
  TO ROLE DEV_ROLE;

-- Step 4: Set final context for deployment
USE ROLE &SNOWSQL_ENVVAR_ROLE;
USE DATABASE &SNOWSQL_ENVVAR_DB;
USE WAREHOUSE &SNOWSQL_ENVVAR_WH;
USE SCHEMA &SNOWSQL_ENVVAR_SCHEMA;